import { sessionFixture } from '../../native/helpers/session-fixture.js';
import { buildAtriaPackageContainer, createNativeId } from '../../../src/native/index.js';
import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { startServer, tearDownServer } from '../_lib/server.js';
import { disableExtensions } from '../_lib/fixtures.js';
import { awaitMainUI } from '../_lib/page.js';
import { seedNativeSessionDataRoot } from './_helpers.js';
let server;
test.beforeAll(async () => {
    const seed = await seedNativeSessionDataRoot({ suffix: 'native-portability' });
    disableExtensions({ dataRoot: seed.dataRoot, names: ['stable-diffusion'] });
    server = await startServer({ batchKey: 'generation', scenarioId: 'native-portability', useExistingDataRoot: seed.dataRoot });
});
test.afterAll(async () => { await tearDownServer(server); });

test('Resource Bundle exports an exact World, reviews without writes and retries the same import at 390px', async ({ page }, info) => {
    test.setTimeout(120000);
    await page.setViewportSize({ width: 390, height: 900 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await page.route('**/api/horde/text-models', route => route.fulfill({ json: [] }));
    await page.route('**/api/horde/status', route => route.fulfill({ json: { ok: false } }));
    await awaitMainUI(page, server.baseURL);
    const original = await page.evaluate(async () => {
        const { nativeProductClient: client } = await import('/scripts/native/product-client.js');
        const world = await client.createWorld('Portable harbor');
        await client.commitWorldRevision(world.worldId, { baseRevisionId: null, content: { baseline: { coast: 'Harbor' }, knowledgeBindingIds: [], assetIds: [], metadata: {} } });
        window.Atria.shell.getWorkspaceHost().openLibraryWorld(world.worldId, world.displayName); return world.worldId;
    });
    const detail = page.locator('[data-atria-native-library="worlds-knowledge"]');
    const downloading = page.waitForEvent('download');
    await detail.getByRole('button', { name: 'Export Resource Bundle', exact: true }).first().click();
    const download = await downloading; expect(download.suggestedFilename()).toMatch(/\.atriabundle$/);
    const bytes = await readFile(await download.path()), bundle = JSON.parse(bytes.toString());
    expect(bundle.root.resourceId).toBe(original); expect(bundle.resources).toHaveLength(1);
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openLibrarySection('worlds'));
    const importer = page.locator('[data-atria-resource-bundle]');
    await importer.getByText('Import Resource Bundle', { exact: true }).click();
    await importer.getByLabel('Resource Bundle file').setInputFiles({ name: 'harbor.atriabundle', mimeType: 'application/json', buffer: bytes });
    await expect(importer).toContainText('1 exact resources will be copied');
    const count = () => page.evaluate(async () => (await (await import('/scripts/native/product-client.js')).nativeProductClient.listWorlds()).filter(item => item.world.displayName === 'Portable harbor').length);
    expect(await count()).toBe(1);
    let attempts = 0; const tokens = [];
    await page.route('**/api/native/studio/resources/bundle/import', async route => {
        tokens.push(route.request().postDataJSON().token);
        if (!attempts++) await route.fulfill({ status: 500, json: { error: 'native_resource_bundle_interrupted', details: { completed: [], retryable: true } } });
        else await route.continue();
    });
    await importer.getByRole('button', { name: 'Import into Library', exact: true }).click();
    await expect(importer.getByRole('alert')).toContainText('Import was interrupted');
    await page.screenshot({ path: info.outputPath('bundle-review-retry-390.png') });
    await importer.getByRole('button', { name: 'Retry import', exact: true }).click();
    await expect(importer).toContainText('Resource Bundle imported into Library.');
    expect(tokens[0]).toEqual(tokens[1]); expect(await count()).toBe(2);
    await importer.getByRole('button', { name: 'Open imported resource', exact: true }).click();
    await expect(page.locator('[data-atria-world-detail]')).not.toHaveAttribute('data-atria-world-detail', original);
    await expect(detail.getByRole('heading', { name: 'Portable harbor', exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('installed World and Knowledge originals browse exact content and fork independent closures', async ({ page }, info) => {
    test.setTimeout(120000); await page.setViewportSize({ width: 390, height: 900 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await page.route('**/api/horde/text-models', route => route.fulfill({ json: [] }));
    await page.route('**/api/horde/status', route => route.fulfill({ json: { ok: false } }));
    await awaitMainUI(page, server.baseURL);
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openLibrarySection('worlds'));
    const list = page.locator('[data-atria-package-resources]');
    await list.getByRole('button', { name: 'Browse original', exact: true }).first().click();
    const original = page.locator('[data-atria-package-original]');
    await expect(original).toContainText('N4 Native Live Package');
    await expect(original).toContainText('harbor');
    await expect(original.getByRole('button', { name: 'New revision', exact: true })).toHaveCount(0);
    await original.getByText('Used By', { exact: true }).click();
    await original.getByRole('button', { name: 'Load references', exact: true }).click();
    await expect(original.locator('[data-atria-package-used-by]')).toContainText('N4 Native Live Package');
    await original.getByText('Fork to Library', { exact: true }).click();
    await original.getByRole('button', { name: 'Review fork', exact: true }).click();
    await expect(original.locator('[data-atria-package-fork-review]')).toContainText('3 exact resources');
    const oldId = await original.getAttribute('data-atria-package-original');
    await page.screenshot({ path: info.outputPath('package-world-fork-390.png') });
    await original.getByRole('button', { name: 'Create fork', exact: true }).click();
    await original.getByRole('button', { name: 'Open imported resource', exact: true }).click();
    await expect(page.locator('[data-atria-world-detail]')).not.toHaveAttribute('data-atria-world-detail', oldId);
    await expect(page.getByRole('button', { name: 'New revision', exact: true })).toBeVisible();
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openLibrarySection('knowledge'));
    await list.getByRole('button', { name: 'Browse original', exact: true }).first().click();
    await expect(original).toContainText('N4_NATIVE_KNOWLEDGE_PAYLOAD');
    await expect(original.getByRole('button', { name: 'New revision', exact: true })).toHaveCount(0);
    await original.getByText('Used By', { exact: true }).click();
    await original.getByRole('button', { name: 'Load references', exact: true }).click();
    await expect(original.locator('[data-atria-package-used-by]')).toContainText('Knowledge Binding');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('Work starts an intentional Session from an installed exact version without changing the default', async ({ page }, info) => {
    test.setTimeout(120000); await page.setViewportSize({ width: 390, height: 900 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await page.route('**/api/horde/text-models', route => route.fulfill({ json: [] }));
    await page.route('**/api/horde/status', route => route.fulfill({ json: { ok: false } }));
    await awaitMainUI(page, server.baseURL);
    const original = await page.evaluate(async () => (await (await import('/scripts/native/product-client.js')).nativeProductClient.listWorks())[0].manifest);
    const next = structuredClone(original); next.packageVersionId = createNativeId('packageVersion'); next.version = '2.0.0'; next.entryPoints[0].entryPointId = createNativeId('entryPoint'); next.entryPoints[0].displayName = 'New edition start';
    const archive = buildAtriaPackageContainer({ manifest: next, sourceFiles: new Map(), assetPayloads: new Map() }).archive.toString('base64');
    await page.evaluate(async ({ archive, id }) => {
        const { nativeProductClient: client } = await import('/scripts/native/product-client.js');
        await client.installPackage(archive, []); window.Atria.shell.getWorkspaceHost().openLibraryWork(id);
    }, { archive, id: original.packageId });
    const row = page.locator('[data-atria-installed-version="' + original.packageVersionId + '"]');
    await row.getByRole('button', { name: 'Start from this version', exact: true }).click();
    await expect(row).toContainText('non-default installed version'); await expect(row).toContainText('default Work version and existing Sessions remain unchanged');
    await expect(row.getByLabel('Starting point', { exact: true })).toHaveValue(original.entryPoints[0].entryPointId);
    await page.screenshot({ path: info.outputPath('installed-version-start-390.png') });
    const response = page.waitForResponse(r => r.url().endsWith('/works/' + original.packageId + '/start') && r.request().method() === 'POST');
    await row.getByRole('button', { name: 'Create Session on this version', exact: true }).click();
    const created = await (await response).json(); expect(created.session.packageVersionId).toBe(original.packageVersionId);
    const current = await page.evaluate(async id => (await (await import('/scripts/native/product-client.js')).nativeProductClient.getWork(id)).package.currentVersionId, original.packageId);
    expect(current).toBe(next.packageVersionId);
});

test('Package update reviews new permissions and preserves Session pins with post-install management', async ({ page }, info) => {
    test.setTimeout(120000); await page.setViewportSize({ width: 390, height: 900 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await page.route('**/api/horde/text-models', route => route.fulfill({ json: [] }));
    await page.route('**/api/horde/status', route => route.fulfill({ json: { ok: false } }));
    await awaitMainUI(page, server.baseURL);
    const old = await page.evaluate(async () => {
        const { nativeProductClient: client } = await import('/scripts/native/product-client.js'); const work = (await client.listWorks())[0];
        const created = await client.startWork(work.package.packageId, { displayTitle: 'Pinned before update' });
        window.Atria.shell.getWorkspaceHost().openLibrarySection('works'); return { manifest: work.manifest, session: created.session };
    });
    const next = structuredClone(old.manifest); next.packageVersionId = createNativeId('packageVersion'); next.version = '3.0.0';
    next.permissions = [{ permission: 'network', required: true, reason: 'Fetch story content' }, { permission: 'clipboard', required: false, reason: 'Copy passages' }];
    const archive = buildAtriaPackageContainer({ manifest: next, sourceFiles: new Map(), assetPayloads: new Map() }).archive;
    const install = page.locator('[data-atria-native-install]'); await install.getByText('Install / Update .atria', { exact: true }).click();
    await install.locator('input[type="file"]').setInputFiles({ name: 'update.atria', mimeType: 'application/octet-stream', buffer: archive });
    await expect(install.locator('[data-atria-package-update-impact]')).toContainText('New permissions');
    await expect(install).toContainText('existing Sessions stay pinned');
    await install.getByRole('button', { name: 'Install / Update', exact: true }).click();
    await expect(install.getByRole('alert')).toContainText('Grant required permissions');
    await install.getByRole('checkbox', { name: 'Network access', exact: true }).check();
    await page.screenshot({ path: info.outputPath('package-update-permissions-390.png') });
    await install.getByRole('button', { name: 'Install / Update', exact: true }).click();
    await expect(page.locator('[data-atria-native-works]')).toContainText('3.0.0');
    await page.evaluate(id => window.Atria.shell.getWorkspaceHost().openLibraryWork(id), next.packageId);
    const permissions = page.locator('[data-atria-work-permissions]'); await permissions.getByText('Work permissions', { exact: true }).click();
    await permissions.getByRole('button', { name: 'Review permissions', exact: true }).click();
    await expect(permissions).toContainText('Required · Accepted at installation'); await expect(permissions).toContainText('Optional declaration · No separate grant recorded');
    await permissions.getByRole('button', { name: 'Manage uninstall and dependent Sessions', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Review dependent Sessions', exact: true })).toBeVisible();
    const state = await page.evaluate(async id => (await (await import('/scripts/native/product-client.js')).nativeProductClient.getSession(id)).snapshot.session, old.session.sessionId);
    expect(state.packageVersionId).toBe(old.manifest.packageVersionId);
});

for (const surface of ['Library', 'Play']) test(surface + ' Save recovery rejects mismatched Work bytes then installs and imports in place', async ({ page }, info) => {
    test.setTimeout(120000); await page.setViewportSize({ width: 390, height: 900 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await page.route('**/api/horde/text-models', route => route.fulfill({ json: [] }));
    await page.route('**/api/horde/status', route => route.fulfill({ json: { ok: false } }));
    await awaitMainUI(page, server.baseURL);
    const fixture = sessionFixture(); fixture.manifest.name = 'Recoverable voyage';
    const archive = buildAtriaPackageContainer({ manifest: fixture.manifest, sourceFiles: new Map(), assetPayloads: new Map() }).archive;
    const wrong = buildAtriaPackageContainer({ manifest: { ...fixture.manifest, name: 'Wrong content' }, sourceFiles: new Map(), assetPayloads: new Map() }).archive;
    const saved = await page.evaluate(async ({ data, packageId, surface }) => {
        const { nativeProductClient: client } = await import('/scripts/native/product-client.js');
        await client.installPackage(data); const created = await client.startWork(packageId);
        const payload = await client.exportSession(created.session.sessionId); await client.deleteSession(created.session.sessionId); await client.deleteWork(packageId);
        const host = window.Atria.shell.getWorkspaceHost(); if (surface === 'Library') host.openLibrarySection('works'); else host.openPlay();
        return { payload, session: created.session };
    }, { data: archive.toString('base64'), packageId: fixture.manifest.packageId, surface });
    const importer = surface === 'Library' ? page.locator('[data-atria-native-save-import]') : page.locator('[data-atria-native-play-landing] .atria-native-portable-save');
    await importer.locator('summary').first().click();
    await importer.locator('input[type="file"]').first().setInputFiles({ name: 'voyage.atriasave', mimeType: 'application/octet-stream', buffer: Buffer.from(saved.payload.data, 'base64') });
    const recovery = importer.locator('[data-atria-save-recovery]'); await expect(recovery).toBeVisible();
    await recovery.getByLabel('Matching Work file', { exact: true }).setInputFiles({ name: 'wrong.atria', mimeType: 'application/octet-stream', buffer: wrong });
    await expect(recovery.getByRole('alert')).toContainText('Nothing was installed');
    await recovery.getByLabel('Matching Work file', { exact: true }).setInputFiles({ name: 'exact.atria', mimeType: 'application/octet-stream', buffer: archive });
    await expect(recovery.getByRole('button', { name: 'Install matching Work', exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath(surface.toLowerCase() + '-save-recovery-390.png') });
    await recovery.getByRole('button', { name: 'Install matching Work', exact: true }).click();
    await expect(importer.locator('[data-atria-save-preflight="ready"]')).toBeVisible();
    await importer.getByRole('button', { name: surface === 'Library' ? 'Import Save' : 'Import & Open', exact: true }).click();
    await page.locator('dialog.popup[open] .popup-button-ok').click();
    await expect.poll(() => page.evaluate(() => window.Atria.nativeSessionRuntime.snapshot?.session.sessionId)).toBe(saved.session.sessionId);
    expect(await page.evaluate(() => window.Atria.nativeSessionRuntime.snapshot.session.packageContentHash)).toBe(saved.session.packageContentHash);
});

test('Session creation and Play/Library rename preserve identity and history at 390px', async ({ page }, info) => {
    test.setTimeout(120000); await page.setViewportSize({ width: 390, height: 900 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await page.route('**/api/horde/text-models', route => route.fulfill({ json: [] }));
    await page.route('**/api/horde/status', route => route.fulfill({ json: { ok: false } }));
    await awaitMainUI(page, server.baseURL);
    const packageId = await page.evaluate(async () => {
        const work = (await (await import('/scripts/native/product-client.js')).nativeProductClient.listWorks())[0];
        window.Atria.shell.getWorkspaceHost().openLibraryWork(work.package.packageId); return work.package.packageId;
    });
    const hero = page.locator('[data-atria-work-detail]'); await hero.getByLabel('Session name (optional)', { exact: true }).fill('Lantern voyage');
    await hero.getByRole('button', { name: 'Start New', exact: true }).click();
    await expect.poll(() => page.evaluate(() => window.Atria.nativeSessionRuntime.snapshot?.session.displayTitle)).toBe('Lantern voyage');
    const before = await page.evaluate(() => window.Atria.nativeSessionRuntime.snapshot.session);
    await page.getByRole('button', { name: 'Timeline', exact: true }).click();
    const rename = page.locator('[data-atria-native-play-drawer] [data-atria-session-rename]'); await rename.getByText('Rename Session', { exact: true }).click();
    await rename.getByLabel('Session name', { exact: true }).fill('My pending name');
    await page.evaluate(async session => {
        const { nativeProductClient: client } = await import('/scripts/native/product-client.js'); await client.renameSession(session.sessionId, 'Concurrent name', session.displayTitle);
    }, before);
    await rename.getByRole('button', { name: 'Save name', exact: true }).click(); await expect(rename.getByRole('alert')).toContainText('changed elsewhere');
    await expect(rename.getByLabel('Session name', { exact: true })).toHaveValue('My pending name');
    await rename.getByRole('button', { name: 'Reload current name', exact: true }).click();
    await rename.getByLabel('Session name', { exact: true }).fill('Renamed voyage'); await rename.getByRole('button', { name: 'Save name', exact: true }).click();
    await expect.poll(() => page.evaluate(() => window.Atria.nativeSessionRuntime.snapshot?.session.displayTitle)).toBe('Renamed voyage');
    await page.screenshot({ path: info.outputPath('session-rename-390.png') });
    await page.keyboard.press('Escape');
    await page.evaluate(id => window.Atria.shell.getWorkspaceHost().openLibraryWork(id), packageId);
    const row = page.locator('[data-atria-my-games] [data-atria-session-id="' + before.sessionId + '"]'); await row.getByText('Manage', { exact: true }).click();
    const libraryRename = row.locator('[data-atria-session-rename]'); await libraryRename.getByText('Rename Session', { exact: true }).click();
    await libraryRename.getByLabel('Session name', { exact: true }).fill('Library voyage'); await libraryRename.getByRole('button', { name: 'Save name', exact: true }).click();
    await expect(row.getByRole('heading', { name: 'Library voyage', exact: true })).toBeVisible();
    const after = await page.evaluate(async id => (await (await import('/scripts/native/product-client.js')).nativeProductClient.getSession(id)).snapshot.session, before.sessionId);
    for (const key of ['sessionId', 'headRevisionId', 'activeBranchId', 'packageVersionId', 'packageContentHash']) expect(after[key]).toBe(before[key]);
});
