import { test, expect } from '@playwright/test';
import { startServer, tearDownServer } from '../_lib/server.js';
import { awaitMainUI } from '../_lib/page.js';
import { seedNativeSessionDataRoot } from './_helpers.js';
let server;
if (process.env.PW_NATIVE_CHANNEL) test.use({ channel: process.env.PW_NATIVE_CHANNEL });

test.beforeAll(async () => {
    const seed = await seedNativeSessionDataRoot({ suffix: 'prompt-presets' });
    server = await startServer({ batchKey: 'generation', scenarioId: 'prompt-presets', useExistingDataRoot: seed.dataRoot });
});

test.afterAll(async () => { await tearDownServer(server); });

for (const width of [1440, 390]) test(`module filtering, action menus and return position at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 800 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await awaitMainUI(page, server.baseURL);
    const presetId = await page.evaluate(async () => {
        const { runtimeRequest } = await import('/scripts/native/runtime-client.js');
        const { newPromptResource } = await import('/scripts/native/prompt-authoring.js');
        const program = newPromptResource('core.prompt-program'), generation = newPromptResource('core.generation-profile');
        const entries = [{ resourceType: 'core.prompt-program', resource: program }, { resourceType: 'core.generation-profile', resource: generation }];
        const moduleCategories = {};
        for (let i = 0; i < 36; i++) {
            const resource = newPromptResource('core.prompt-module'); resource.displayName = 'Module ' + i;
            entries.push({ resourceType: 'core.prompt-module', resource });
            if (i < 34) moduleCategories[resource.promptModuleId] = i % 2 ? 'cat_child' : 'cat_deep';
        }
        return (await runtimeRequest('/presets', { method: 'POST', body: { preset: {
            format: 'atria.prompt-preset', schemaVersion: 1, programId: program.promptProgramId, entries, moduleCategories,
            categories: [{ id: 'cat_root', name: 'Root', parentId: null }, { id: 'cat_child', name: 'Child', parentId: 'cat_root' }, { id: 'cat_deep', name: 'Deep', parentId: 'cat_child' }, { id: 'cat_empty', name: 'Empty', parentId: null }],
        } } })).presetId;
    });
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openLibrarySection('prompt-presets'));
    await page.locator(`[data-atri-preset-id="${presetId}"]`).getByRole('button', { name: 'Open preset', exact: true }).click();
    await page.getByRole('button', { name: 'Prompt Modules', exact: true }).click();
    const filter = page.getByRole('combobox', { name: 'Filter by category', exact: true });
    const rows = page.locator('.atri-module-row');
    await expect(rows).toHaveCount(36);
    await expect(page.getByRole('button', { name: 'Category actions', exact: true })).toBeDisabled();
    await filter.selectOption('uncategorized'); await expect(rows).toHaveCount(2);
    await filter.selectOption('cat_empty'); await expect(rows).toHaveCount(0);
    await expect(page.getByText('No modules in this category.', { exact: true })).toBeVisible();
    await filter.selectOption('cat_root'); await expect(rows).toHaveCount(34);
    await filter.selectOption('cat_deep'); await expect(rows).toHaveCount(17);
    await filter.selectOption('cat_child'); await expect(rows).toHaveCount(34);
    const target = rows.filter({ has: page.getByRole('button', { name: 'Module 28', exact: true }) });
    await target.scrollIntoViewIfNeeded();
    const before = await target.boundingBox();
    await target.getByRole('button', { name: 'Module 28', exact: true }).click();
    await page.getByRole('button', { name: 'Back to resources', exact: true }).click();
    await expect(filter).toHaveValue('cat_child');
    await expect(target.getByRole('button', { name: 'Module 28', exact: true })).toBeFocused();
    expect(Math.abs((await target.boundingBox()).y - before.y)).toBeLessThan(3);
    await target.getByRole('button', { name: 'Module actions', exact: true }).click();
    await expect(page.getByRole('menuitem', { name: 'View / edit parameters', exact: true })).toBeFocused();
    await page.keyboard.press('End'); await expect(page.getByRole('menuitem', { name: 'Delete module', exact: true })).toBeFocused();
    await page.keyboard.press('Escape'); await expect(page.getByRole('menu')).toHaveCount(0);
    await expect(target.getByRole('button', { name: 'Module actions', exact: true })).toBeFocused();
    await target.getByRole('button', { name: 'Module actions', exact: true }).click();
    await page.screenshot({ path: info.outputPath('module-menu.png') });
    const box = await page.getByRole('menu').boundingBox(); expect(box.x).toBeGreaterThanOrEqual(0); expect(box.x + box.width).toBeLessThanOrEqual(width);
    await page.getByRole('menuitem', { name: 'View / edit parameters', exact: true }).click();
    await page.getByRole('textbox', { name: 'Prompt body', exact: true }).fill('Updated body');
    await page.getByRole('button', { name: 'Save revision', exact: true }).click();
    await expect(filter).toHaveValue('cat_child'); await expect(target).toBeVisible();
    expect(Math.abs((await target.boundingBox()).y - before.y)).toBeLessThan(3);
    await filter.selectOption('cat_root');
    await page.getByRole('button', { name: 'Category actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Move category', exact: true }).click();
    const parent = page.getByRole('combobox', { name: 'Parent category', exact: true });
    await expect(parent).toHaveValue('');
    await expect(parent.locator('option')).toHaveCount(2); // Top level + Empty; descendants cannot become parents.
    await page.locator('dialog[open] .popup-button-cancel').click();
    await filter.selectOption('cat_child');
    await page.getByRole('button', { name: 'Category actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Move category', exact: true }).click();
    await parent.selectOption('cat_empty');
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(filter).toHaveValue('cat_child');
    await expect(rows.first()).toContainText('Empty / Child');
    await filter.selectOption('cat_root'); await expect(rows).toHaveCount(0);
    await filter.selectOption('cat_empty'); await expect(rows).toHaveCount(34);
    await page.screenshot({ path: info.outputPath('module-filter.png') });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole('button', { name: 'Module list actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Create category', exact: true }).click();
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(page.getByRole('textbox', { name: 'Category name', exact: true })).toBeFocused();
    await page.locator('dialog[open] .popup-button-cancel').click();
    await page.getByRole('button', { name: 'Module list actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'New module', exact: true }).click();
    await page.getByRole('textbox', { name: 'Display name', exact: true }).fill('Created in selected category');
    await page.getByRole('button', { name: 'Save revision', exact: true }).click();
    const created = rows.filter({ has: page.getByRole('button', { name: 'Created in selected category', exact: true }) });
    await expect(created).toContainText('Empty');
    await expect(rows).toHaveCount(35);
    await created.getByRole('button', { name: 'Module actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Delete module', exact: true }).click();
    await page.locator('dialog[open] .popup-button-cancel').click();
    await expect(created).toHaveCount(1);
    await created.getByRole('button', { name: 'Module actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Delete module', exact: true }).click();
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(rows).toHaveCount(34);
    await expect(filter).toHaveValue('cat_empty');
    // A slow configuration observer must not keep a committed category move stale.
    await page.evaluate(async () => {
        const { onRuntimeConfigurationChanged } = await import('/scripts/native/runtime-client.js');
        window.releasePresetObserver = null;
        window.removePresetObserver = onRuntimeConfigurationChanged(() => new Promise(resolve => { window.releasePresetObserver = resolve; }));
    });
    const moved = rows.filter({ has: page.getByRole('button', { name: 'Module 28', exact: true }) });
    await moved.getByRole('button', { name: 'Module actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Move module', exact: true }).click();
    await page.getByRole('combobox', { name: 'Module category', exact: true }).selectOption('cat_root');
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(rows).toHaveCount(33);
    await expect(moved).toHaveCount(0);
    await filter.selectOption('cat_root');
    await expect(moved).toHaveCount(1);
    await page.evaluate(() => { window.releasePresetObserver(); window.removePresetObserver(); });
});

for (const width of [1440, 390]) test(`Preset Regex editor, bulk controls and portable ownership at ${width}px`, async ({ page }, info) => {
    test.setTimeout(120000);
    await page.setViewportSize({ width, height: 960 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await awaitMainUI(page, server.baseURL);
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openLibrarySection('prompt-presets'));
    await page.getByRole('button', { name: 'New preset', exact: true }).click();
    const presetId = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    await page.getByRole('button', { name: 'Preset Regex', exact: true }).click();
    await page.getByRole('button', { name: 'New Regex rule', exact: true }).click();
    const dialog = page.locator('dialog[open]');
    await dialog.locator('.regex_script_name').fill('Portable rule');
    await dialog.locator('.find_regex').fill('/before/g');
    await dialog.locator('.regex_replace_string').fill('after');
    await dialog.locator('input[name="replace_position"][value="1"]').check();
    await dialog.locator('.popup-button-ok').click();
    await expect(page.getByRole('checkbox', { name: 'Portable rule', exact: true })).toBeVisible();
    await page.getByRole('checkbox', { name: 'Portable rule', exact: true }).check();
    await page.getByRole('button', { name: 'Disable selected rules', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset] article')).toContainText('Disabled');
    await page.getByRole('checkbox', { name: 'Portable rule', exact: true }).check();
    await page.getByRole('button', { name: 'Enable selected rules', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset] article')).toContainText('Enabled');
    await expect(page.getByLabel('Import Regex rules', { exact: true })).toBeVisible();
    await page.getByLabel('Import Regex rules', { exact: true }).setInputFiles({
        name: 'rules.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ id: 'portable-id', scriptName: 'Imported rule', findRegex: '/after/g', replaceString: 'final', placement: [1] })),
    });
    await page.getByRole('button', { name: 'Import selected rules', exact: true }).click();
    await expect(page.getByRole('checkbox', { name: 'Imported rule', exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath('preset-regex.png') });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole('button', { name: 'Back to presets', exact: true }).click();
    const downloadPromise = page.waitForEvent('download');
    await page.locator(`[data-atri-preset-id="${presetId}"]`).getByRole('button', { name: 'Export preset', exact: true }).click();
    const exportedPath = info.outputPath('preset-regex.json'); await (await downloadPromise).saveAs(exportedPath);
    await expect(page.getByLabel('Import preset', { exact: true })).toBeVisible();
    await page.getByLabel('Import preset', { exact: true }).setInputFiles(exportedPath);
    await page.getByRole('button', { name: 'Import selected preset', exact: true }).click();
    const importedId = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    await expect(page.locator('[data-atri-prompt-preset]')).not.toHaveAttribute('data-atri-prompt-preset', presetId);
    await page.getByRole('button', { name: 'Preset Regex', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset] article')).toHaveCount(2);
    const readPresets = () => page.evaluate(async ({ presetId, importedId }) => {
        const { runtimeRequest: request } = await import('/scripts/native/runtime-client.js');
        return Promise.all([request('/presets/' + presetId), request('/presets/' + importedId)]);
    }, { presetId, importedId });
    const [original, imported] = await readPresets();
    expect(imported.regexScripts).toEqual(original.regexScripts);
    await page.getByRole('checkbox', { name: 'Portable rule', exact: true }).check();
    await page.getByRole('button', { name: 'Disable selected rules', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset] article').first()).toContainText('Disabled');
    const [unchanged, changed] = await readPresets();
    expect(unchanged.regexScripts[0].disabled).toBe(false);
    expect(changed.regexScripts[0].disabled).toBe(true);
    await page.getByRole('button', { name: 'Back to presets', exact: true }).click();
    await page.locator(`[data-atri-preset-id="${importedId}"]`).getByRole('button', { name: 'Delete preset', exact: true }).click();
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(page.locator(`[data-atri-preset-id="${importedId}"]`)).toHaveCount(0);
    await expect(page.locator(`[data-atri-preset-id="${presetId}"]`)).toBeVisible();
});

test('migrates existing resources without exposing loose modules inside the preset', async ({ page }) => {
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await awaitMainUI(page, server.baseURL);
    const source = await page.evaluate(async () => {
        const { runtimeRequest: request } = await import('/scripts/native/runtime-client.js');
        const { newPromptResource, resourceRef } = await import('/scripts/native/prompt-authoring.js');
        const module = newPromptResource('core.prompt-module'); module.displayName = 'Legacy module';
        const orphan = newPromptResource('core.prompt-module'); orphan.displayName = 'Loose module'; orphan.body = 'Independent copy';
        const program = newPromptResource('core.prompt-program'); program.displayName = 'Legacy suite';
        program.stages[0].moduleRefs = [resourceRef('core.prompt-module', module, { scope: 'library' })];
        const generation = newPromptResource('core.generation-profile'); generation.displayName = 'Legacy settings'; generation.sampling = { temperature: 0.3 };
        for (const [resourceType, resource] of [['core.prompt-module', module], ['core.prompt-module', orphan], ['core.prompt-program', program], ['core.generation-profile', generation]]) await request('/resources', { method: 'POST', body: { resourceType, resource } });
        window.Atria.shell.getWorkspaceHost().openLibrarySection('prompt-programs');
        return { module, orphan, program, generation };
    });
    await page.getByText('Existing resources — migrate into an independent preset', { exact: true }).click();
    await page.getByRole('button', { name: 'Choose existing resources', exact: true }).click();
    await page.getByRole('combobox', { name: 'Prompt Programs', exact: true }).selectOption({ label: 'Legacy suite · library · ' + source.program.revision });
    await page.getByRole('combobox', { name: 'Generation Profiles', exact: true }).selectOption({ label: 'Legacy settings · library · ' + source.generation.revision });
    await page.getByRole('button', { name: 'Create independent preset', exact: true }).click();
    await page.getByRole('button', { name: 'Prompt Modules', exact: true }).click();
    await expect(page.getByRole('combobox', { name: 'Filter by category' })).toContainText('Legacy suite');
    await expect(page.getByRole('button', { name: 'Copy existing module', exact: true })).toHaveCount(0);
    await expect(page.locator('[data-atri-prompt-preset]')).not.toContainText('Loose module');
    const id = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    const preset = await page.evaluate(async id => (await import('/scripts/native/runtime-client.js')).runtimeRequest('/presets/' + id), id);
    expect(preset.entries.filter(e => e.resourceType === 'core.prompt-module')).toHaveLength(1);
    expect(preset.entries.some(e => e.resource.promptModuleId === source.orphan.promptModuleId)).toBe(false);
    expect(preset.entries.find(e => e.resourceType === 'core.generation-profile').resource.sampling.temperature).toBe(0.3);
});

for (const width of [1440, 390]) test(`preset ownership, nested categories and export/import at ${width}px`, async ({ page }, info) => {
    test.setTimeout(120000);
    await page.setViewportSize({ width, height: 960 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await awaitMainUI(page, server.baseURL);
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openLibrarySection('prompt-presets'));
    await page.getByRole('button', { name: 'New preset', exact: true }).click();
    const presetId = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    await expect(page.getByRole('button', { name: 'Generation Profiles', exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath('preset.png') });
    await page.getByRole('button', { name: 'Prompt Modules', exact: true }).click();
    await page.getByRole('button', { name: 'Module list actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Create category', exact: true }).click();
    await page.getByRole('textbox', { name: 'Category name', exact: true }).fill('Root');
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(page.getByRole('combobox', { name: 'Filter by category' })).toContainText('Root');
    await page.getByRole('button', { name: 'Module list actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Create category', exact: true }).click();
    await page.getByRole('textbox', { name: 'Category name', exact: true }).fill('Child');
    await page.getByRole('combobox', { name: 'Parent category', exact: true }).selectOption({ label: 'Root' });
    await page.locator('dialog[open] .popup-button-ok').click();
    const filter = page.getByRole('combobox', { name: 'Filter by category' });
    await expect(filter).toContainText('└ Child');
    await page.getByRole('button', { name: 'Module list actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'New module', exact: true }).click();
    await page.getByRole('textbox', { name: 'Display name', exact: true }).fill('My module');
    await page.getByRole('textbox', { name: 'Prompt body', exact: true }).fill('Preset-owned content');
    await page.getByRole('button', { name: 'Save revision', exact: true }).click();
    await page.getByRole('button', { name: 'Module actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Move module', exact: true }).click();
    await page.getByRole('combobox', { name: 'Module category', exact: true }).selectOption({ index: 2 });
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(page.locator('.atri-module-row')).toContainText('Root / Child');
    await filter.selectOption({ label: 'Root' });
    await expect(page.locator('.atri-module-row')).toContainText('My module');
    await filter.selectOption({ index: 3 });
    await page.getByRole('button', { name: 'Category actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Rename category', exact: true }).click();
    await page.getByRole('textbox', { name: 'Category name', exact: true }).fill('Renamed');
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(filter).toContainText('└ Renamed');
    await page.screenshot({ path: info.outputPath('categories.png') });
    await page.getByRole('button', { name: 'Back to preset', exact: true }).click();
    await page.getByRole('button', { name: 'Prompt Programs', exact: true }).click();
    await page.getByRole('combobox', { name: 'Module for stage 1', exact: true }).selectOption({ index: 1 });
    await page.getByRole('button', { name: 'Add module', exact: true }).click();
    await page.getByRole('button', { name: 'Save revision', exact: true }).click();
    await page.getByRole('button', { name: 'Back to presets', exact: true }).click();
    const downloadPromise = page.waitForEvent('download');
    await page.locator(`[data-atri-preset-id="${presetId}"]`).getByRole('button', { name: 'Export preset', exact: true }).click();
    const download = await downloadPromise;
    const exportPath = info.outputPath('preset.json'); await download.saveAs(exportPath);
    await page.getByLabel('Import preset', { exact: true }).setInputFiles(exportPath);
    await page.getByRole('button', { name: 'Import selected preset', exact: true }).click();
    const importedId = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    await expect(page.locator('[data-atri-prompt-preset]')).not.toHaveAttribute('data-atri-prompt-preset', presetId);
    await page.getByRole('button', { name: 'Prompt Modules', exact: true }).click();
    await expect(page.locator('.atri-module-row')).toContainText('Root / Renamed');
    await filter.selectOption({ label: 'Root' });
    await page.getByRole('button', { name: 'Category actions', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Delete category', exact: true }).click();
    await expect(page.locator('dialog[open]')).toContainText('My module');
    await expect(page.locator('dialog[open]')).toContainText('Affected programs');
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(filter.locator('option')).toHaveCount(2);
    await expect(page.locator('.atri-prompt-preset')).toContainText('No modules yet');
    const data = await page.evaluate(async ({ presetId, importedId }) => {
        const { runtimeRequest: request } = await import('/scripts/native/runtime-client.js');
        return { original: await request('/presets/' + presetId), imported: await request('/presets/' + importedId) };
    }, { presetId, importedId });
    expect(data.original.entries.find(e => e.resourceType === 'core.prompt-program').resource.stages[0].moduleRefs).toHaveLength(1);
    expect(data.imported.entries.find(e => e.resourceType === 'core.prompt-program').resource.stages[0].moduleRefs).toHaveLength(0);
    expect(data.original.categories).toHaveLength(2);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.evaluate(ref => window.Atria.shell.getWorkspaceHost().openLibraryResource(ref), data.original.refs.find(r => r.resourceType === 'core.prompt-program'));
    const exact = page.locator('.atri-prompt-resource[data-selected="true"]');
    await expect(exact).toBeVisible();
    await exact.getByRole('button', { name: 'Open preset', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset]')).toHaveAttribute('data-atri-prompt-preset', presetId);
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openRuntimeSection('routes'));
    await page.getByRole('button', { name: 'New route', exact: true }).click();
    await page.getByRole('combobox', { name: 'Prompt Preset', exact: true }).selectOption(presetId);
    const programChoice = page.getByRole('combobox', { name: 'Prompt — exact revision', exact: true });
    const generationChoice = page.getByRole('combobox', { name: 'Generation — exact revision', exact: true });
    await expect(programChoice).toBeDisabled(); await expect(generationChoice).toBeDisabled();
    expect(JSON.parse(await programChoice.inputValue()).resourceId).toBe(presetId);
    expect(JSON.parse(await generationChoice.inputValue()).resourceId).toBe(data.original.entries.find(e => e.resourceType === 'core.generation-profile').resource.generationProfileId);
});
