import { test, expect } from '@playwright/test';
import { startServer, tearDownServer } from '../_lib/server.js';
import { awaitMainUI } from '../_lib/page.js';
import { seedNativeSessionDataRoot } from './_helpers.js';
let server;
if (process.env.PW_NATIVE_CHANNEL) test.use({ channel: process.env.PW_NATIVE_CHANNEL });

test.beforeAll(async () => {
    const seed = await seedNativeSessionDataRoot({ suffix: 'prompt-presets' });
    server = await startServer({ batchKey: 'generation', scenarioId: 'prompt-presets', useExistingDataRoot: seed.dataRoot });
});

test.afterAll(async () => { await tearDownServer(server); });

for (const width of [1440, 390]) test(`Preset Regex editor, bulk controls and portable ownership at ${width}px`, async ({ page }, info) => {
    test.setTimeout(120000);
    await page.setViewportSize({ width, height: 960 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await awaitMainUI(page, server.baseURL);
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openLibrarySection('prompt-presets'));
    await page.getByRole('button', { name: 'New preset', exact: true }).click();
    const presetId = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    await page.getByRole('button', { name: 'Preset Regex', exact: true }).click();
    await page.getByRole('button', { name: 'New Regex rule', exact: true }).click();
    const dialog = page.locator('dialog[open]');
    await dialog.locator('.regex_script_name').fill('Portable rule');
    await dialog.locator('.find_regex').fill('/before/g');
    await dialog.locator('.regex_replace_string').fill('after');
    await dialog.locator('input[name="replace_position"][value="1"]').check();
    await dialog.locator('.popup-button-ok').click();
    await expect(page.getByRole('checkbox', { name: 'Portable rule', exact: true })).toBeVisible();
    await page.getByRole('checkbox', { name: 'Portable rule', exact: true }).check();
    await page.getByRole('button', { name: 'Disable selected rules', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset] article')).toContainText('Disabled');
    await page.getByRole('checkbox', { name: 'Portable rule', exact: true }).check();
    await page.getByRole('button', { name: 'Enable selected rules', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset] article')).toContainText('Enabled');
    await expect(page.getByLabel('Import Regex rules', { exact: true })).toBeVisible();
    await page.getByLabel('Import Regex rules', { exact: true }).setInputFiles({
        name: 'rules.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ id: 'portable-id', scriptName: 'Imported rule', findRegex: '/after/g', replaceString: 'final', placement: [1] })),
    });
    await page.getByRole('button', { name: 'Import selected rules', exact: true }).click();
    await expect(page.getByRole('checkbox', { name: 'Imported rule', exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath('preset-regex.png') });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole('button', { name: 'Back to presets', exact: true }).click();
    const downloadPromise = page.waitForEvent('download');
    await page.locator(`[data-atri-preset-id="${presetId}"]`).getByRole('button', { name: 'Export preset', exact: true }).click();
    const exportedPath = info.outputPath('preset-regex.json'); await (await downloadPromise).saveAs(exportedPath);
    await expect(page.getByLabel('Import preset', { exact: true })).toBeVisible();
    await page.getByLabel('Import preset', { exact: true }).setInputFiles(exportedPath);
    await page.getByRole('button', { name: 'Import selected preset', exact: true }).click();
    const importedId = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    await expect(page.locator('[data-atri-prompt-preset]')).not.toHaveAttribute('data-atri-prompt-preset', presetId);
    await page.getByRole('button', { name: 'Preset Regex', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset] article')).toHaveCount(2);
    const readPresets = () => page.evaluate(async ({ presetId, importedId }) => {
        const { runtimeRequest: request } = await import('/scripts/native/runtime-client.js');
        return Promise.all([request('/presets/' + presetId), request('/presets/' + importedId)]);
    }, { presetId, importedId });
    const [original, imported] = await readPresets();
    expect(imported.regexScripts).toEqual(original.regexScripts);
    await page.getByRole('checkbox', { name: 'Portable rule', exact: true }).check();
    await page.getByRole('button', { name: 'Disable selected rules', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset] article').first()).toContainText('Disabled');
    const [unchanged, changed] = await readPresets();
    expect(unchanged.regexScripts[0].disabled).toBe(false);
    expect(changed.regexScripts[0].disabled).toBe(true);
    await page.getByRole('button', { name: 'Back to presets', exact: true }).click();
    await page.locator(`[data-atri-preset-id="${importedId}"]`).getByRole('button', { name: 'Delete preset', exact: true }).click();
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(page.locator(`[data-atri-preset-id="${importedId}"]`)).toHaveCount(0);
    await expect(page.locator(`[data-atri-preset-id="${presetId}"]`)).toBeVisible();
});

test('migrates existing resources without exposing loose modules inside the preset', async ({ page }) => {
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await awaitMainUI(page, server.baseURL);
    const source = await page.evaluate(async () => {
        const { runtimeRequest: request } = await import('/scripts/native/runtime-client.js');
        const { newPromptResource, resourceRef } = await import('/scripts/native/prompt-authoring.js');
        const module = newPromptResource('core.prompt-module'); module.displayName = 'Legacy module';
        const orphan = newPromptResource('core.prompt-module'); orphan.displayName = 'Loose module'; orphan.body = 'Independent copy';
        const program = newPromptResource('core.prompt-program'); program.displayName = 'Legacy suite';
        program.stages[0].moduleRefs = [resourceRef('core.prompt-module', module, { scope: 'library' })];
        const generation = newPromptResource('core.generation-profile'); generation.displayName = 'Legacy settings'; generation.sampling = { temperature: 0.3 };
        for (const [resourceType, resource] of [['core.prompt-module', module], ['core.prompt-module', orphan], ['core.prompt-program', program], ['core.generation-profile', generation]]) await request('/resources', { method: 'POST', body: { resourceType, resource } });
        window.Atria.shell.getWorkspaceHost().openLibrarySection('prompt-programs');
        return { module, orphan, program, generation };
    });
    await page.getByText('Existing resources — migrate into an independent preset', { exact: true }).click();
    await page.getByRole('button', { name: 'Choose existing resources', exact: true }).click();
    await page.getByRole('combobox', { name: 'Prompt Programs', exact: true }).selectOption({ label: 'Legacy suite · library · ' + source.program.revision });
    await page.getByRole('combobox', { name: 'Generation Profiles', exact: true }).selectOption({ label: 'Legacy settings · library · ' + source.generation.revision });
    await page.getByRole('button', { name: 'Create independent preset', exact: true }).click();
    await page.getByRole('button', { name: 'Prompt Modules', exact: true }).click();
    await expect(page.locator('.atri-preset-category summary')).toHaveText('Legacy suite');
    await expect(page.getByRole('button', { name: 'Copy existing module', exact: true })).toHaveCount(0);
    await expect(page.locator('[data-atri-prompt-preset]')).not.toContainText('Loose module');
    const id = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    const preset = await page.evaluate(async id => (await import('/scripts/native/runtime-client.js')).runtimeRequest('/presets/' + id), id);
    expect(preset.entries.filter(e => e.resourceType === 'core.prompt-module')).toHaveLength(1);
    expect(preset.entries.some(e => e.resource.promptModuleId === source.orphan.promptModuleId)).toBe(false);
    expect(preset.entries.find(e => e.resourceType === 'core.generation-profile').resource.sampling.temperature).toBe(0.3);
});

for (const width of [1440, 390]) test(`preset ownership, nested categories and export/import at ${width}px`, async ({ page }, info) => {
    test.setTimeout(120000);
    await page.setViewportSize({ width, height: 960 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await awaitMainUI(page, server.baseURL);
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openLibrarySection('prompt-presets'));
    await page.getByRole('button', { name: 'New preset', exact: true }).click();
    const presetId = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    await expect(page.getByRole('button', { name: 'Generation Profiles', exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath('preset.png') });
    await page.getByRole('button', { name: 'Prompt Modules', exact: true }).click();
    await page.getByRole('textbox', { name: 'Category name', exact: true }).fill('Root');
    await page.getByRole('button', { name: 'Create category', exact: true }).click();
    await expect(page.locator('.atri-preset-category')).toHaveCount(1);
    await page.getByRole('textbox', { name: 'Category name', exact: true }).fill('Child');
    await page.getByRole('combobox', { name: 'Parent category', exact: true }).selectOption({ label: 'Root' });
    await page.getByRole('button', { name: 'Create category', exact: true }).click();
    await expect(page.locator('.atri-preset-category')).toHaveCount(2);
    await page.getByRole('button', { name: 'New module', exact: true }).click();
    await page.getByRole('textbox', { name: 'Display name', exact: true }).fill('My module');
    await page.getByRole('textbox', { name: 'Prompt body', exact: true }).fill('Preset-owned content');
    await page.getByRole('button', { name: 'Save revision', exact: true }).click();
    await page.getByRole('combobox', { name: 'Module category', exact: true }).selectOption({ label: 'Root / Child' });
    await page.getByRole('button', { name: 'Move module', exact: true }).click();
    await expect(page.locator('.atri-preset-category .atri-preset-category')).toContainText('My module');
    const child = page.locator('.atri-preset-category .atri-preset-category');
    await child.getByRole('textbox', { name: 'Rename category', exact: true }).fill('Renamed');
    await child.getByRole('button', { name: 'Save category name', exact: true }).click();
    await expect(child.locator('summary')).toHaveText('Renamed');
    await page.screenshot({ path: info.outputPath('categories.png') });
    await page.getByRole('button', { name: 'Back to preset', exact: true }).click();
    await page.getByRole('button', { name: 'Prompt Programs', exact: true }).click();
    await page.getByRole('combobox', { name: 'Module for stage 1', exact: true }).selectOption({ index: 1 });
    await page.getByRole('button', { name: 'Add module', exact: true }).click();
    await page.getByRole('button', { name: 'Save revision', exact: true }).click();
    await page.getByRole('button', { name: 'Back to presets', exact: true }).click();
    const downloadPromise = page.waitForEvent('download');
    await page.locator(`[data-atri-preset-id="${presetId}"]`).getByRole('button', { name: 'Export preset', exact: true }).click();
    const download = await downloadPromise;
    const exportPath = info.outputPath('preset.json'); await download.saveAs(exportPath);
    await page.getByLabel('Import preset', { exact: true }).setInputFiles(exportPath);
    await page.getByRole('button', { name: 'Import selected preset', exact: true }).click();
    const importedId = await page.locator('[data-atri-prompt-preset]').getAttribute('data-atri-prompt-preset');
    await expect(page.locator('[data-atri-prompt-preset]')).not.toHaveAttribute('data-atri-prompt-preset', presetId);
    await page.getByRole('button', { name: 'Prompt Modules', exact: true }).click();
    await expect(page.locator('.atri-preset-category .atri-preset-category')).toContainText('My module');
    await page.locator('.atri-preset-category').first().getByRole('button', { name: 'Delete category', exact: true }).first().click();
    await expect(page.locator('dialog[open]')).toContainText('My module');
    await expect(page.locator('dialog[open]')).toContainText('Affected programs');
    await page.locator('dialog[open] .popup-button-ok').click();
    await expect(page.locator('.atri-preset-category')).toHaveCount(0);
    await expect(page.locator('.atri-prompt-preset')).toContainText('No modules yet');
    const data = await page.evaluate(async ({ presetId, importedId }) => {
        const { runtimeRequest: request } = await import('/scripts/native/runtime-client.js');
        return { original: await request('/presets/' + presetId), imported: await request('/presets/' + importedId) };
    }, { presetId, importedId });
    expect(data.original.entries.find(e => e.resourceType === 'core.prompt-program').resource.stages[0].moduleRefs).toHaveLength(1);
    expect(data.imported.entries.find(e => e.resourceType === 'core.prompt-program').resource.stages[0].moduleRefs).toHaveLength(0);
    expect(data.original.categories).toHaveLength(2);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.evaluate(ref => window.Atria.shell.getWorkspaceHost().openLibraryResource(ref), data.original.refs.find(r => r.resourceType === 'core.prompt-program'));
    const exact = page.locator('.atri-prompt-resource[data-selected="true"]');
    await expect(exact).toBeVisible();
    await exact.getByRole('button', { name: 'Open preset', exact: true }).click();
    await expect(page.locator('[data-atri-prompt-preset]')).toHaveAttribute('data-atri-prompt-preset', presetId);
    await page.evaluate(() => window.Atria.shell.getWorkspaceHost().openRuntimeSection('routes'));
    await page.getByRole('button', { name: 'New route', exact: true }).click();
    await page.getByRole('combobox', { name: 'Prompt Preset', exact: true }).selectOption(presetId);
    const programChoice = page.getByRole('combobox', { name: 'Prompt — exact revision', exact: true });
    const generationChoice = page.getByRole('combobox', { name: 'Generation — exact revision', exact: true });
    await expect(programChoice).toBeDisabled(); await expect(generationChoice).toBeDisabled();
    expect(JSON.parse(await programChoice.inputValue()).resourceId).toBe(presetId);
    expect(JSON.parse(await generationChoice.inputValue()).resourceId).toBe(data.original.entries.find(e => e.resourceType === 'core.generation-profile').resource.generationProfileId);
});
