import { test, expect } from '@playwright/test';
import { startServer, tearDownServer } from '../_lib/server.js';
import { awaitMainUI } from '../_lib/page.js';
import { createAndOpenNativeSession, seedNativeSessionDataRoot } from './_helpers.js';

if (process.env.PW_NATIVE_CHANNEL) test.use({ channel: process.env.PW_NATIVE_CHANNEL });
let server, sessionStart;
test.describe.configure({ mode: 'serial' });

test.beforeAll(async () => {
    const seeded = await seedNativeSessionDataRoot({ suffix: 'extensions-ui' });
    sessionStart = seeded.start;
    server = await startServer({ batchKey: 'generation', scenarioId: 'extensions-ui', useExistingDataRoot: seeded.dataRoot });
});

test.afterAll(async () => { await tearDownServer(server, { removeData: true }); });

for (const width of [1440, 320]) test(`Extensions script and Skill settings at ${width}px`, async ({ page }, info) => {
    test.setTimeout(150000);
    await page.setViewportSize({ width, height: 1000 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await page.route('**/api/horde/**', route => route.fulfill({ json: [] }));
    await awaitMainUI(page, server.baseURL);
    await page.evaluate(async () => {
        await window.Atria.getContext().skills.importBundled();
        window.Atria.shell.getWorkspaceHost().openUtility('plugins');
    });
    const root = page.locator('[data-atria-utility-workspace="extensions"]');
    await expect(root.getByRole('heading', { name: 'Extensions', exact: true })).toBeVisible();
    await root.locator('summary').filter({ hasText: /^New folder$/ }).click();
    await root.getByLabel('New folder', { exact: true }).fill('Methods ' + width);
    await root.getByRole('button', { name: 'Create folder', exact: true }).click();
    await expect(root.getByText('Methods ' + width, { exact: true }).last()).toBeVisible();
    const row = root.locator('[data-skill-name]').first();
    await row.getByText('Folder and invocation paths', { exact: true }).click();
    await row.getByLabel('Folder', { exact: true }).selectOption({ label: 'Methods ' + width });
    await row.getByLabel('Studio', { exact: true }).selectOption('always');
    await row.getByLabel('Narrative', { exact: true }).selectOption('off');
    await row.getByRole('button', { name: 'Save Skill settings', exact: true }).click();
    await expect(root.locator('[data-skill-folder]').filter({ has: page.locator('summary', { hasText: 'Methods ' + width }) }).locator('[data-skill-name]')).toHaveCount(1);
    await root.locator('.atri-skill-organization').getByLabel('Folder', { exact: true }).selectOption({ label: 'Methods ' + width });
    await root.evaluate(node => { node.scrollTop = 0; });
    await page.screenshot({ path: info.outputPath(`skills-${width}.png`), fullPage: true });
    await root.locator('[data-skill-folder]').filter({ has:page.locator('summary',{ hasText:'Methods ' + width }) }).locator('[data-skill-action="edit"]').click(); const popup = page.locator('dialog.popup[open]'); const skill = popup.locator('.atria_skill_editor'); const textarea = skill.locator('[data-editor-textarea]'); await expect(textarea).toBeVisible(); const original = await textarea.inputValue(); const pending = original + '\nB4 full file Source draft'; await textarea.fill(pending);
    await skill.locator('[data-file-path]:not([data-file-path="SKILL.md"]):not([data-editor-action])').first().click(); await expect(textarea).not.toHaveValue(pending); await skill.locator('[data-file-path="SKILL.md"]:not([data-editor-action])').click(); await expect(textarea).toHaveValue(pending);
    await page.screenshot({ path:info.outputPath('b4-skill-source-' + width + '.png'),fullPage:true }); await skill.locator('[data-editor-save]').click(); await expect(skill.locator('[data-editor-status]')).toContainText('Saved SKILL.md'); await popup.locator('.popup-button-ok').click(); await expect(popup).toBeHidden();
    await root.locator('[data-extension-tab="plugins"]').click();
    await root.getByRole('button', { name: 'Local scripts', exact: true }).click();
    await root.getByRole('button', { name: 'New script', exact: true }).click();
    await root.getByLabel('Name', { exact: true }).fill('UI fixture ' + width);
    await root.getByLabel('JavaScript', { exact: true }).fill('export function activate(atria) { const node = document.createElement("div"); node.id = "extension-ui-fixture"; node.textContent = "Fixture active"; atria.ui.mount(node); }');
    await root.getByLabel('Global', { exact: true }).check();
    await root.getByLabel('Enabled', { exact: true }).check();
    await page.screenshot({ path: info.outputPath(`script-editor-${width}.png`), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
    expect((await root.getByLabel('JavaScript', { exact: true }).boundingBox()).height).toBeGreaterThanOrEqual(260);
    await root.getByLabel('JavaScript', { exact: true }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: info.outputPath(`script-code-${width}.png`), fullPage: true });
    await root.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(root.getByRole('heading', { name: 'UI fixture ' + width, exact: true })).toBeVisible();
    await expect(page.locator('#extension-ui-fixture')).toBeVisible();
    const card = root.locator('[data-extension-id]').filter({ hasText: 'UI fixture ' + width });
    await card.getByRole('button', { name: 'Edit', exact: true }).click();
    await root.getByLabel('Enabled', { exact: true }).uncheck();
    await root.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.locator('#extension-ui-fixture')).toHaveCount(0);
    await root.getByLabel('Import JavaScript', { exact: true }).setInputFiles({ name: 'imported.js', mimeType: 'text/javascript', buffer: Buffer.from('export function activate() {}') });
    await expect(root.getByLabel('Name', { exact: true })).toHaveValue('imported');
    await expect(root.getByLabel('Enabled', { exact: true })).not.toBeChecked();
    await root.getByRole('button', { name: 'Cancel', exact: true }).click();
    await root.getByRole('button', { name: 'Built-in tools', exact: true }).click();
    await expect(root.getByRole('heading', { name: 'Regex', exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
});


test('A3 official Illustration retains the full settings draft and exposes Session tools at 390px', async ({ page }, info) => {
    test.setTimeout(150000); await page.setViewportSize({ width: 390, height: 844 });
    await page.addInitScript(() => localStorage.setItem('language', 'en'));
    await page.route('**/api/horde/**', route => route.fulfill({ json: [] })); await awaitMainUI(page, server.baseURL);
    await page.evaluate(() => Atria.shell.getWorkspaceHost().openUtility('plugins'));
    const root = page.locator('[data-atria-utility-workspace="extensions"]');
    await root.locator('[data-extension-tab="plugins"]').click(); await root.getByRole('button', { name: '官方插件', exact: true }).click();
    const settings = root.locator('.atri-illustration-ui'); await expect(settings.getByLabel('风格词', { exact: true })).toBeVisible();
    await settings.getByLabel('启用官方插图插件', { exact: true }).check();
    await settings.getByLabel('风格词', { exact: true }).fill('A3 illustration style');
    await settings.getByText('全局绘图角色库', { exact: true }).click();
    await settings.getByRole('button', { name: '新增角色', exact: true }).click();
    await settings.getByLabel('姓名', { exact: true }).fill('A3 drawing character');
    await settings.getByLabel('别名（每行一个）', { exact: true }).fill('Atria drawing\nA3');
    await settings.getByLabel('固定外观提示词', { exact: true }).fill('blue eyes');
    await settings.getByLabel('默认服装', { exact: true }).fill('coat');
    page.once('dialog', dialog => dialog.dismiss()); await root.locator('[data-extension-tab="skills"]').click();
    await expect(settings.getByLabel('姓名', { exact: true })).toHaveValue('A3 drawing character');
    await expect(settings.getByLabel('风格词', { exact: true })).toHaveValue('A3 illustration style');
    await settings.getByRole('button', { name:'Source',exact:true }).click(); const source = settings.getByLabel('Illustration settings JSON',{ exact:true }); const valid = await source.inputValue();
    await source.fill('{ incomplete'); await settings.getByRole('button',{ name:'Fields',exact:true }).click(); await expect(source).toHaveValue('{ incomplete');
    const settingsDraft = JSON.parse(valid); settingsDraft.preset.parameters.seed = -1; settingsDraft.preset.parameters.sm = true; await source.fill(JSON.stringify(settingsDraft,null,2));
    await page.screenshot({ path:info.outputPath('b4-illustration-source-390.png'),fullPage:true }); await settings.getByRole('button',{ name:'Fields',exact:true }).click(); await expect(settings.getByLabel('NovelAI 参数',{ exact:true })).toHaveValue(/"seed": -1/);
    await settings.getByRole('button', { name: '保存配置', exact: true }).click(); await expect(settings).toContainText('配置已保存。');
    await root.getByRole('button', { name: 'Local scripts', exact: true }).click();
    await expect(root.getByRole('button', { name: 'New script', exact: true })).toBeVisible();
    await root.getByRole('button', { name: '官方插件', exact: true }).click();
    await expect(settings.getByLabel('风格词', { exact: true })).toHaveValue('A3 illustration style');
    await settings.getByText('全局绘图角色库', { exact: true }).click();
    const characterId = await settings.getByLabel('编辑绘图角色', { exact: true }).locator('option').last().getAttribute('value');
    await settings.getByLabel('编辑绘图角色', { exact: true }).selectOption(characterId);
    await expect(settings.getByLabel('姓名', { exact: true })).toHaveValue('A3 drawing character');
    await page.screenshot({ path: info.outputPath('a3-illustration-settings-390.png'), fullPage: true });
    const session = await createAndOpenNativeSession(page, sessionStart);
    const tools = page.locator('[data-atria-official-illustration="true"]');
    await expect(tools).toBeAttached();
    await expect(tools).toBeHidden();
    await page.evaluate(() => Atria.shell.getWorkspaceHost().openPlay());
    await expect(page.locator('#atria-app-shell')).toHaveAttribute('data-atria-reading', 'true');
    await expect(tools.getByRole('button', { name: '正文模式', exact: true })).toBeVisible();
    await tools.getByRole('button', { name: '标注与历史', exact: true }).click();
    await expect(tools.getByText('开启生图模式，选择一段正文来创建标注。', { exact: true })).toBeVisible();
    await tools.getByRole('button', { name: '关闭卡片', exact: true }).click();
    await tools.getByRole('button', { name: '插图配置', exact: true }).click();
    await expect(tools.getByLabel('配置范围', { exact: true })).toHaveValue(sessionStart.packageId);
    await tools.getByLabel('覆盖作品预设', { exact: true }).check();
    await tools.getByLabel('风格词', { exact: true }).fill('Unsaved work override');
    page.once('dialog', dialog => dialog.dismiss()); await tools.getByRole('button', { name: '关闭配置', exact: true }).click();
    await expect(tools.getByLabel('风格词', { exact: true })).toHaveValue('Unsaved work override');
    expect((await page.evaluate(() => Atria.nativeSessionRuntime.snapshot.session)).sessionId).toBe(session.sessionId);
    await page.screenshot({ path: info.outputPath('a3-illustration-session-390.png'), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});
