import assert from 'node:assert/strict';
export async function convergenceChecks(h) {
 const {act,actNative,fresh,value,session,load,svc,fsHandle,archive,native,manifest,sourceFiles,safe,makeTempFsEngine,services,freeText,projectInformation}=h;
 const {readContent,validateContent}=await import('./content-check.mjs');const resources=await readContent();const content=validateContent(resources,manifest);
 for(const mutate of [r=>delete r.get('cases.signature.company').value.items[0].runtime,r=>r.get('cases.signature.hearing').value.items[0].canon.revelationPredicates=['completed_count'],r=>r.get('cases.signature.accident').value.items[0].runtime.sources[1].dangerous=false,r=>r.get('cases.signature.headline').value.items[0].runtime.sources[0].text='界'.repeat(300),r=>delete r.get('cases.patterns.network_b').value.items[0].canon.requiredEvidenceRoles]){const copy=structuredClone(resources);mutate(copy);assert.throws(()=>validateContent(copy,manifest));}
 const kits=['company','accident','headline'].map(k=>resources.get('cases.signature.'+k).value.items[0]);
 const catalog=[...resources.get('defs.claims.seeds').value.items,...resources.get('defs.claims.archetypes').value.items];
 const {prepareAuthorityTransaction,buildAuthorityObservation}=await load('src/native/authority-transaction.js');
 const result={phase:'P7',prepared:0,nativeCommits:0,typed:0,checks:[],maximumWork:{readGrants:0,appCommands:0,effects:0},maximumObservationBytes:0};
 const v=(base,id,record='main')=>base.states.atri_lifecycle.domains[id].records.find(r=>r.id===record)?.value;
 const cv=base=>v(base,'opening_summary_projection').convergence;
 await fresh();let base=await svc.core.appendTimeline(fsHandle,session().session.sessionId,{role:'user',content:'P7 contract matrix'});
 const installed=await svc.core._openPackage(fsHandle,base.session.packageId,base.session.packageVersionId,base.session.entryPointId);
 const prepare=async(b,id,input={},expected='automatic',ordinal=0)=>{const before=structuredClone(b);const p=await prepareAuthorityTransaction(b,installed,{transactionId:id,input,anchor:buildAuthorityObservation(b).anchor,playerMessageId:b.timeline.at(-1).messageId,ordinal});assert.deepEqual(b,before);if(expected)assert.equal(p.receipt.result.outcome,expected,id);safe(p.receipt);result.prepared++;for(const key of Object.keys(result.maximumWork))result.maximumWork[key]=Math.max(result.maximumWork[key],p.work[key]);assert(p.work.readGrants<=16&&p.work.appCommands<=24&&p.work.effects<=32);const next={...b,states:p.candidate.states};const obs=buildAuthorityObservation(next);safe(obs);assert(JSON.stringify(obs).includes('player.convergence.status'),'Resolver must retain the compact P7 status even when evidence is truncated');const bytes=Buffer.byteLength(JSON.stringify(obs));result.maximumObservationBytes=Math.max(result.maximumObservationBytes,bytes);console.error('PASS P7 prepare',id,p.receipt.result.outcome,JSON.stringify(p.work));return next;};
 const inputManage=(key,operation='open',disposition='none')=>({case:key,operation,disposition});
 const manage=(b,k,op='open',dis='none',expect='automatic')=>prepare(b,'convergence.manage',inputManage(k,op,dis),expect);
 const source=(b,k,i,expect='automatic')=>prepare(b,'convergence.source_'+i%2,{method:kits.find(a=>a.runtime.key===k).runtime.sources[i].method},expect);
 const dims={history:'attributed_public',stability:'preserve_arrangements',justice:'compensation',power:'shared_council',religion:'dual_registry',accountability:'independent_audit'};
 const catInput=(a,operation)=>({item:a.id,rule:a.canon.coreRule,condition:a.canon.condition??a.canon.conditionFamily,primitive:a.canon.primitive,tradition:'civic',operation,acceptPrice:true});
 const hearing=(b,operation,terms=dims,expect='automatic')=>prepare(b,'convergence.hearing',{operation,...terms},expect);
 if(!process.argv.includes('--convergence-live')) {
 base=await manage(base,'company','open','none','impossible');assert.equal(cv(base).cases.company.mandate,false);
 // Real P5 declarations establish the baseline; no P7 authority is patched by tests.
 for(const [id,input] of [['identity',{name:'P7 Verifier',pronouns:'they',age:31,appearance:'Work coat'}],['origin',{choice:'origin.clerical_household'}],['prior_life',{choice:'prior_life.legal'}],['faith',{choice:'faith.distanced'}],['anchor',{name:'Rin',relationship:'friend',place:'office'}],['reason',{reason:'Preserve qualified public records.'}],['acquire_mortuary',{method:'inspect_death'}],['acquire_register',{method:'request_old_register'}],['compare',{method:'compare_independent_sources'}],['preserve',{method:'separate_and_witness'}]])base=await prepare(base,'opening.'+id,input);
 if(process.argv.includes('--convergence-fortune')){
  let trial=await manage(base,'accident');trial=await manage(trial,'accident','prepare');let automatic=false,costly=false;
  for(let ordinal=0;ordinal<64&&(!automatic||!costly);ordinal++){const next=await prepare(trial,'convergence.source_1',{method:'isolated_trial'},null,ordinal);assert(cv(next).evidence.accident.s1.known);const graph=h.queryInformationGraph(next,'player.case_graph','main',{purpose:'display'});safe(graph);assert(JSON.stringify(graph).includes('accident_s1'));if(v(next,'world_matters').report_due)costly=true;else automatic=true;}
  assert(automatic&&costly);result.checks.push('Actual bounded trial reaches both Automatic and Costly outcomes across distinct ordinals; both retain observation, Costly adds reporting duty');return result;
 }
 base=await hearing(base,'petition',dims,'impossible');assert.equal(cv(base).eligible,false);
 const orders=[['company','accident','headline'],['headline','company','accident'],['accident','headline','company']];
 let supported;
 for(const order of orders){let b=base;for(const k of order){b=await manage(b,k);b=await source(b,k,0);b=await source(b,k,2);if(k!=='accident')assert.equal(cv(b).eligible,false);b=await source(b,k,3);}assert(cv(b).eligible);assert.equal(v(b,'settlements').convergence.company.disposition,'none');assert.equal(v(b,'world_matters').network.property.mandate,false);assert.equal(v(b,'world_matters').network.burial.mandate,false);assert.equal(v(b,'world_matters').network.railway.mandate,false);supported=b;}
 result.checks.push('Three Network B orders; same-side duplicates reject; convergence with all three P6 Signatures missed and no B dispositions');
 let unsafe=await manage(base,'accident');const evidence=structuredClone(v(unsafe,'evidence','network'));unsafe=await source(unsafe,'accident',1,'impossible');assert.deepEqual(v(unsafe,'evidence','network'),evidence);unsafe=await manage(unsafe,'accident','prepare');const a=await source(unsafe,'accident',1,null),b=await source(unsafe,'accident',1,null);assert.deepEqual(a.states,b.states,'Same anchor trial remains stable');assert(cv(a).evidence.accident.s1.known);
 for(const k of ['company','accident','headline'])for(const disposition of kits.find(a=>a.runtime.key===k).runtime.dispositions){const b=await manage(supported,k,'settle',disposition.id);assert.equal(v(b,'settlements').convergence[k].disposition,disposition.id);assert.equal(cv(b).cases[k].protected,disposition.id!=='withdraw');assert(cv(b).eligible);}
 result.checks.push('Twelve qualified B dispositions; denied unprepared inert trial; same-anchor bounded trial');
 let final=await hearing(supported,'petition');assert(cv(final).cases.petition);final=await hearing(final,'examine');assert(cv(final).layers.deep_inquiry);assert(cv(final).evidence.residual.known);safe(projectInformation(final,'narrator.context',{purpose:'context'}));assert(v(final,'investigation_nodes_projection').convergence.eligible);assert(v(final,'investigation_nodes_projection').convergence.evidence.residual.known);const graph=h.queryInformationGraph(final,'player.case_graph','main',{purpose:'display'});safe(graph);assert(JSON.stringify(graph).includes('eastbank_residual'));
 const alternatives={history:['attributed_public','protected_archive','qualified_summary'],stability:['preserve_arrangements','phased_revision','local_containment'],justice:['compensation','recognition_review','defer_remedy'],power:['civic_oversight','shared_council','local_autonomy'],religion:['sacred_recognition','dual_registry','civil_priority'],accountability:['independent_audit','named_duties','protected_inquiry']};
 for(const [key,options]of Object.entries(alternatives))for(const selected of options){const terms={...dims,[key]:selected};const end=await hearing(final,'settle',terms);for(const [d,x]of Object.entries(terms)){assert.equal(cv(end).settlements.hearing[d],x);assert.equal(v(end,'institutional_records').convergence[d],x);}assert.equal(cv(end).settlements.hearing.compensation_due,terms.justice==='compensation');}
 result.checks.push('All eighteen dimension alternatives preserve the other five terms independently; residual inquiry remains non-final');
 // Alternative cross-source route without press/accident: burial + rail + company.
 let alternate=await manage(base,'company');alternate=await source(alternate,'company',2);alternate=await source(alternate,'company',3);
 for(const [k,methods]of [['burial',['parish_extract','negative_search']],['railway',['record_perimeter','certified_dispatch']]]){alternate=await prepare(alternate,'network.open',{case:k});for(const method of methods)alternate=await prepare(alternate,'network.acquire_'+k,{method});}
 assert(cv(alternate).eligible);alternate=await hearing(alternate,'petition');assert(!cv(alternate).cases.headline.mandate);assert(!cv(alternate).cases.accident.mandate);
 let late=base;while(v(late,'world_matters').day<24)late=await prepare(late,'opening.wait',{minutes:2880});for(const k of ['company','accident','headline'])assert(cv(late).cases[k].expired);assert(cv(late).cases.standardized&&cv(late).cases.locked);
 const families=[...resources.get('cases.patterns.network_a').value.items,...resources.get('cases.patterns.network_b').value.items];
 const practice=async(b,family,slot='p0',operation='open',disposition='none')=>{const p=v(b,'world_matters').convergence[slot];return prepare(b,'convergence.practice',{slot,family,claimant:'Ordinary applicant',operation,disposition,due:p.opened?p.due:v(b,'world_matters').day+7});};
 for(const family of families){let p=await practice(base,family.id);p=await practice(p,family.id,'p0','request');p=await practice(p,family.id,'p0','reply');p=await practice(p,family.id,'p0','settle','qualified_remedy');p=await practice(p,family.id,'p0','fulfil','qualified_remedy');assert(v(p,'world_matters').convergence.p0.fulfilled);}
 let form=await practice(supported,'matter.pattern.document_conservation');form=await practice(form,'matter.pattern.document_conservation','p0','request');form=await practice(form,'matter.pattern.document_conservation','p0','reply');
 // P5 formal Claim remains the precondition for established archetypes.
 for(const [id,input]of [['seed_unlost_evidence',{seed:'claim.seed.unlost_evidence'}],['consult',{method:'qualified_civic_or_church_consultation'}],['stabilize_unlost_evidence_civic',{tradition:'civic',seed:'claim.seed.unlost_evidence',acceptPrice:true}]])form=await prepare(form,'opening.'+id,input);
 for(const [k,methods]of [['property',['registry_copy','estate_extract']],['railway',['record_perimeter','certified_dispatch']]]){form=await prepare(form,'network.open',{case:k});for(const method of methods)form=await prepare(form,'network.acquire_'+k,{method});}
 const exercised=new Set();
 const firstNew=catalog.find(a=>a.id==='claim.seed.custody_break');let newInvested=await prepare(supported,'convergence.claim',catInput(firstNew,'consult'));newInvested=await prepare(newInvested,'convergence.claim',catInput(firstNew,'invest'));assert(v(newInvested,'progression').invested);assert.equal(v(newInvested,'conditions').strained,false);
 for(const item of catalog){let c=await prepare(form,'convergence.claim',catInput(item,'consult'));c=await prepare(c,'convergence.claim',catInput(item,'invest'));assert.equal(v(c,'claims').catalog.item,item.id);if(exercised.has(item.canon.primitive))continue;exercised.add(item.canon.primitive);c=await prepare(c,'convergence.claim',catInput(item,'invoke'),'impossible');c=await prepare(c,'convergence.claim',catInput(item,'maintain'));c=await prepare(c,'convergence.claim',catInput(item,'invoke'));assert(v(c,'claims').catalog.applied);assert(v(c,'claims').catalog.price_due);assert.equal(v(c,'institutional_records').catalog.item,item.id);}
 await assert.rejects(prepare(form,'convergence.claim',{...catInput(catalog[0],'consult'),rule:catalog[1].canon.coreRule}));
 result.checks.push('Ten independent Pattern families and fulfilment; all sixteen Seeds and thirty-two archetypes pass canonical consultation/Investiture; all eight primitives exercise paid-before-use invocation and renewed Price');
 while(v(late,'world_matters').day<30)late=await prepare(late,'opening.wait',{minutes:2880});const before=structuredClone(late);await assert.rejects(prepare(late,'opening.wait',{minutes:1440}));assert.deepEqual(late,before);result.checks.push('Day10/12/14 pressure, day18 standardization and day24 lock survive non-discovery; atomic day31 refusal');
 }
 if(process.argv.includes('--convergence-state'))return result;
 // Actual Native Turn commits, HTTP typed/free-text retry and save containers.
 await fresh();
 const live=async(id,input={},expect='automatic')=>{await actNative(id,input,expect);result.nativeCommits++;};
 for(const [id,input] of [['identity',{name:'P7 Verifier',pronouns:'they',age:31,appearance:'Work coat'}],['origin',{choice:'origin.clerical_household'}],['prior_life',{choice:'prior_life.legal'}],['faith',{choice:'faith.distanced'}],['anchor',{name:'Rin',relationship:'friend',place:'office'}],['reason',{reason:'Keep incomplete evidence.'}],['acquire_mortuary',{method:'inspect_death'}],['acquire_register',{method:'request_old_register'}],['compare',{method:'compare_independent_sources'}],['preserve',{method:'separate_and_witness'}]])await live('opening.'+id,input);
 for(const k of ['company','headline']){await live('convergence.manage',inputManage(k));for(const i of [0,3])await live('convergence.source_'+i%2,{method:kits.find(a=>a.runtime.key===k).runtime.sources[i].method});}
 assert(value('opening_summary_projection').convergence.eligible);
 await act('convergence.hearing',{operation:'petition',...dims});result.typed++;await freeText('convergence.hearing',{operation:'examine',...dims});await live('convergence.hearing',{operation:'settle',...dims});
 const liveFamily='matter.pattern.document_conservation',due=value('world_matters').day+7;
 for(const operation of ['open','request','reply','settle'])await live('convergence.practice',{slot:'p0',family:liveFamily,claimant:'Ordinary applicant',operation,disposition:operation==='settle'?'qualified_remedy':'none',due});
 const liveItem=catalog.find(a=>a.id==='claim.seed.custody_break');for(const operation of ['consult','invest','maintain','invoke'])await live('convergence.claim',catInput(liveItem,operation));
 assert(value('claims').catalog.active&&value('claims').catalog.applied&&value('claims').catalog.price_due);
 const save=await svc.saveSystem.manualSave(fsHandle,session().session.sessionId);const bytes=await svc.saveSystem.exportSnapshot(fsHandle,session().session.sessionId,save.saveId);const target=await makeTempFsEngine();try{const next=services(target);await next.packageInstaller.install(target.handle,archive,{grantedPermissions:['generation']});const restored=await next.saveSystem.importSave(target.handle,bytes.archive);assert.deepEqual(v(restored,'settlements').convergence,v(session(),'settlements').convergence);assert.deepEqual(v(restored,'evidence','network').convergence,v(session(),'evidence','network').convergence);assert.deepEqual(v(restored,'claims').catalog,v(session(),'claims').catalog);assert.equal(v(restored,'world_matters').convergence.p0.disposition,'qualified_remedy');const continued=await next.core.applyLifecycleCommand(target.handle,restored.session.sessionId,{type:'lifecycle',invocationId:'p7-restored-day',action:{kind:'clock.advance',commandId:'advance',ticks:1440}},{expectedRevisionId:restored.revision.revisionId});assert.equal(v(continued,'settlements').convergence.hearing.history,dims.history);assert.equal(v(continued,'world_matters').day,v(restored,'world_matters').day+1);result.checks.push('Actual manual save export/import into a fresh FS preserves final six-dimensional terms and acquired carriers');}finally{await target.cleanup();}
 result.checks.push('Native Turn commits; typed HTTP and free-text failure-zero-publication/retry');return result;
}
