// Build-time declarations only; Core remains the sole evaluator, scheduler and authority.
export function compileConvergence(opening, kits, patterns, catalog) {
 const {logic,lifecycle,information}=opening, pub=logic.derivedPublications[0];
 const F=formula=>({formula}), S=(maxLength=256,values)=>({type:'string',maxLength,...(values?{enum:values}:{})}), B={type:'boolean'}, I=(minimum=0,maximum=30)=>({type:'integer',minimum,maximum});
 const O=properties=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
 const D=id=>lifecycle.domains.find(d=>d.id===id);
 const fields=(schema,path)=>schema.type==='object'?Object.fromEntries(Object.entries(schema.properties).map(([k,s])=>[k,fields(s,path+'.'+k)])):F(path);
 const read=(id,domainId,fs,recordId='main')=>({id,domainId,recordId,fields:fs});
 const cmd=(d,id,props,assign)=>D(d).commands.push({id,argsSchema:O(props),assign,event:d+'.'+id});
 const eff=(domainId,commandId,args={},when,recordId='main')=>({kind:'app.command',domainId,commandId,recordId,args,...(when?{when}:{})});
 const add=(d,key,schema,initial)=>{const x=D(d);x.recordSchema.properties[key]=schema;x.recordSchema.required.push(key);x.initial[key]=initial;const boot=x.commands.find(c=>c.id==='bootstrap');if(boot)boot.assign[key]=structuredClone(initial);};
 const tx=(id,props,reads,allowed,effects,notice,minutes=0)=>{const t={id:'convergence.'+id,verb:'convergence_'+id,inputSchema:O(props),intent:{expose:true,description:notice},reads,validators:[],resolution:{kind:'deterministic',cases:[{id:'impossible',when:'!('+allowed+')',outcome:'impossible'}],fallback:'automatic'},effects:[{kind:'world.event',type:'OpeningAction',payload:{verb:'convergence.'+id,outcome:F('resolution.outcome')}},...effects.map(e=>({...e,when:'resolution.outcome != "impossible"'+(e.when?' && ('+e.when+')':'')})),...(minutes?[{kind:'clock.advance',commandId:'advance',ticks:minutes,when:'resolution.outcome != "impossible"'}]:[])],derivedPublications:['opening.publish'],receipt:{schema:O({verb:S(64),outcome:S(32),notice:S(1024)}),projection:{verb:'convergence.'+id,outcome:F('resolution.outcome'),notice},maxBytes:2048}};logic.transactions.push(t);return t;};
 const keys=kits.map(a=>a.runtime.key), choose=k=>'args.case == "'+k+'"', any=fn=>keys.map(k=>'('+choose(k)+' && ('+fn(k)+'))').join(' || ');
 const E=O({text:S(512),known:B}), blank={text:'',known:false};
 const CE=O(Object.fromEntries(['s0','s1','s2','s3'].map(k=>[k,E]))), emptyCase=Object.fromEntries(['s0','s1','s2','s3'].map(k=>[k,structuredClone(blank)]));
 const ES=O({...Object.fromEntries(keys.map(k=>[k,CE])),residual:E,p0_request:S(256),p0_reply:S(256),p1_request:S(256),p1_reply:S(256)});
 add('evidence','convergence',ES,{...Object.fromEntries(keys.map(k=>[k,structuredClone(emptyCase)])),residual:structuredClone(blank),p0_request:'',p0_reply:'',p1_request:'',p1_reply:''});
 // Reuse the already bootstrapped bounded evidence/network record and its one read.
 const P=O({mandate:B,prepared:B,expired:B,protected:B}), p={mandate:false,prepared:false,expired:false,protected:false};
 const Pattern=O({family:S(64),claimant:S(64),opened:B,request:B,reply:B,disposition:S(32),due:I(0,37),expired:B,fulfilled:B});
 const pat={family:'',claimant:'',opened:false,request:false,reply:false,disposition:'none',due:0,expired:false,fulfilled:false};
 const WM=O({...Object.fromEntries(keys.map(k=>[k,P])),worker_veto:B,split_custody:B,charter_maintenance:B,instrument_restricted:B,independent_controls:B,public_protocol:B,public_correction:B,protected_bulletin:B,petition:B,deep_inquiry:B,standardized:B,locked:B,compact_filed:B,p0:Pattern,p1:Pattern,designation_held:B,carrier_held:B,boundary_held:B,bond_held:B,echo_examined:B,form_held:B,alternatives_held:B,attribution_held:B});
 const wm={...Object.fromEntries(keys.map(k=>[k,structuredClone(p)])),worker_veto:false,split_custody:false,charter_maintenance:false,instrument_restricted:false,independent_controls:false,public_protocol:false,public_correction:false,protected_bulletin:false,petition:false,deep_inquiry:false,standardized:false,locked:false,compact_filed:false,p0:structuredClone(pat),p1:structuredClone(pat),designation_held:false,carrier_held:false,boundary_held:false,bond_held:false,echo_examined:false,form_held:false,alternatives_held:false,attribution_held:false};add('world_matters','convergence',WM,wm);
 const ST=O({disposition:S(32),accepted_by:S(128),changed:S(256),benefit:S(256),cost:S(256)}), st={disposition:'none',accepted_by:'none',changed:'No current arrangement.',benefit:'none',cost:'none'};
 const dims={history:['attributed_public','protected_archive','qualified_summary'],stability:['preserve_arrangements','phased_revision','local_containment'],justice:['compensation','recognition_review','defer_remedy'],power:['civic_oversight','shared_council','local_autonomy'],religion:['sacred_recognition','dual_registry','civil_priority'],accountability:['independent_audit','named_duties','protected_inquiry']};
 const Final=O({...Object.fromEntries(Object.entries(dims).map(([k,v])=>[k,S(32,['none',...v])])),filed:B,compensation_due:B,recognition_due:B,audit_due:B,source_exposure:B});
 const fi={...Object.fromEntries(Object.keys(dims).map(k=>[k,'none'])),filed:false,compensation_due:false,recognition_due:false,audit_due:false,source_exposure:false};
 add('settlements','convergence',O({...Object.fromEntries(keys.map(k=>[k,ST])),hearing:Final}),{...Object.fromEntries(keys.map(k=>[k,structuredClone(st)])),hearing:fi});
 add('institutional_records','convergence',Final,structuredClone(fi));
 add('beliefs','circulated_account',B,false);
 const daily=D('world_matters').commands.find(c=>c.id==='day');
 for(const a of kits){const k=a.runtime.key;daily.assign['convergence.'+k+'.expired']=F('world.convergence.'+k+'.expired || (world.day + 1 >= '+a.runtime.dueDay+' && !world.convergence.'+k+'.protected)');}
 daily.assign['convergence.standardized']=F('world.convergence.standardized || world.day + 1 >= 18');daily.assign['convergence.locked']=F('world.convergence.locked || (world.day + 1 >= 24 && !world.convergence.compact_filed)');
 for(const s of ['p0','p1'])daily.assign['convergence.'+s+'.expired']=F('world.convergence.'+s+'.expired || (world.convergence.'+s+'.opened && !world.convergence.'+s+'.fulfilled && world.day + 1 >= world.convergence.'+s+'.due)');
 const W=read('wm','world_matters',['day','convergence','network']), EV=read('ev','evidence',['network','convergence'],'network'), PR=read('pr','progression',['breached','verified','preserved','invested']), SET=read('settled','settlements',['convergence']);
 const root='reads.ev.convergence', pair=(k,r=root)=>'('+r+'.'+k+'.s0.known || '+r+'.'+k+'.s2.known) && ('+r+'.'+k+'.s1.known || '+r+'.'+k+'.s3.known)', mandate=k=>'reads.wm.convergence.'+k+'.mandate';
 // Two source-role families each reserve six writes rather than twelve; selectors
 // are finite methods and cannot select arbitrary fields, payloads or targets.
 for(const role of [0,1]){const sources=kits.flatMap(a=>a.runtime.sources.filter((s,i)=>i%2===role).map(s=>({a,s}))), effects=[];
  for(const {a,s} of sources){const id='p7_'+s.id;cmd('evidence',id,{}, {['convergence.'+a.runtime.key+'.'+s.slot]:{text:s.id+' | '+s.issuer+' | '+s.kind+': '+s.text,known:true}});effects.push(eff('evidence',id,{},'args.method == "'+s.method+'"','network'));}
  const allowed=sources.map(({a,s})=>'('+JSON.stringify(s.method)+' == args.method && '+mandate(a.runtime.key)+(s.dangerous?' && reads.wm.convergence.accident.prepared':'')+')').join(' || ');
  const t=tx('source_'+role,{method:S(40,sources.map(x=>x.s.method))},[W],allowed,effects,'Acquire an authorized independent source; the method never reveals a private archive or universal causal Truth. The inert-sample trial requires isolation and consent; denied trials leave alternate documentary routes.',10);
  if(role===1){t.resolution={kind:'bounded_fortune',sides:6,cases:[...t.resolution.cases,{id:'bounded_trial_cost',when:'args.method == "isolated_trial" && resolution.roll <= 2',outcome:'costly'}],fallback:'automatic'};cmd('world_matters','trial_followup',{}, {report_due:true,report_filed:false});t.effects.push(eff('world_matters','trial_followup',{},'resolution.outcome == "costly"'));t.receipt.projection.notice='A prepared isolated trial may require an additional safety report; it cannot change past injury or predict every accident. Other acquisitions are draw-independent. Costly trial retains its valid observation.';}
 }
 const manageEffects=[];
 for(const a of kits){const k=a.runtime.key,base='convergence.'+k;
  cmd('world_matters','p7_manage_'+k,{}, {[base+'.mandate']:true,[base+'.prepared']:F('world.'+base+'.prepared || args.prepare')});
  // operation is declared in command schema, not inferred from caller context.
  D('world_matters').commands.at(-1).argsSchema=O({prepare:B});
  manageEffects.push(eff('world_matters','p7_manage_'+k,{prepare:F('args.operation == "prepare"')},choose(k)+' && args.operation != "settle"'));
  cmd('settlements','p7_settle_'+k,{disposition:S(32,a.runtime.dispositions.map(s=>s.id))},{[base+'.disposition']:F('args.disposition'),[base+'.accepted_by']:'Participating '+k+' custodians',[base+'.changed']:'Qualified arrangement; consult the declared disposition terms. Prior events persist.',[base+'.benefit']:'Current rights follow the recorded term, not an adjudicated deep cause.',[base+'.cost']:'Conflicting claims and maintenance duties remain.'});
  manageEffects.push(eff('settlements','p7_settle_'+k,{disposition:F('args.disposition')},choose(k)+' && args.operation == "settle"'));
  const terms={company:{worker_veto:'coexist',split_custody:'split',charter_maintenance:'reanchor'},accident:{instrument_restricted:'restrict',independent_controls:'regulate',public_protocol:'research'},headline:{public_correction:'publish_incomplete',protected_bulletin:'controlled'}}[k];
  cmd('world_matters','p7_protect_'+k,{protect:B,...Object.fromEntries(Object.keys(terms).map(t=>[t,B]))},{[base+'.protected']:F('args.protect'),...Object.fromEntries(Object.keys(terms).map(t=>['convergence.'+t,F('args.'+t)]))});manageEffects.push(eff('world_matters','p7_protect_'+k,{protect:F('args.disposition != "withdraw"'),...Object.fromEntries(Object.entries(terms).map(([t,d])=>[t,F('args.disposition == "'+d+'"')]))},choose(k)+' && args.operation == "settle"'));
 }
 const dispositions=[...new Set(kits.flatMap(a=>a.runtime.dispositions.map(s=>s.id)))];
 const m=tx('manage',{case:S(16,keys),operation:S(16,['open','prepare','settle']),disposition:S(32,['none',...dispositions])},[W,EV,PR],'reads.pr.breached && ('+any(k=>'(args.operation == "open" && !'+mandate(k)+' && args.disposition == "none") || (args.operation == "prepare" && '+mandate(k)+' && args.disposition == "none") || (args.operation == "settle" && '+mandate(k)+' && (args.disposition == "withdraw" || ('+pair(k)+')) && ('+kits.find(a=>a.runtime.key===k).runtime.dispositions.map(s=>'args.disposition == "'+s.id+'"').join(' || ')+'))')+')',manageEffects,'Open, prepare or settle one consented mandate. Case-specific terms are exact: '+kits.flatMap(a=>a.runtime.dispositions.filter(s=>s.id!=='withdraw').map(s=>s.id+': '+s.changed)).join(' ').slice(0,750),10);
 // Four independent predicate families; at least one non-company source family
 // is necessary, and neither settlement choices nor completion counts are read.
 const predicates=r=>({incomplete:'(('+pair('burial',r+'.network')+') || ('+pair('headline',r+'.convergence')+'))',deliberate:'('+pair('company',r+'.convergence')+')',dependence:'(('+pair('property',r+'.network')+') || ('+pair('company',r+'.convergence')+'))',active:'('+r+'.network.property.s3.known || ('+pair('railway',r+'.network')+') || ('+pair('headline',r+'.convergence')+'))'});
 const predicatesNow=predicates('reads.ev'), qualifies=Object.values(predicatesNow).join(' && ');
 cmd('world_matters','p7_petition',{}, {'convergence.petition':true});cmd('world_matters','p7_residual',{}, {'convergence.deep_inquiry':true});
 cmd('evidence','p7_residual',{}, {'convergence.residual':{text:'eastbank_residual | Joint Academy and community custody | Finding: Supervised comparison finds surviving boundary/identity carriers that the current models do not jointly explain. Their origin remains undetermined; an older structure is a research hypothesis, not a discovered creator.',known:true}});
 const fp=Object.fromEntries(Object.entries(dims).map(([k,v])=>[k,S(32,v)]));
 const compactProps={...fp,compensation_due:B,recognition_due:B,audit_due:B,source_exposure:B};
 for(const d of ['settlements','institutional_records'])cmd(d,'p7_compact',compactProps,{[d==='settlements'?'convergence.hearing':'convergence']:{...Object.fromEntries(Object.keys(compactProps).map(k=>[k,F('args.'+k)])),filed:true}});
 cmd('world_matters','p7_compact',{}, {'convergence.compact_filed':true});
 const hearing=tx('hearing',{operation:S(16,['petition','examine','settle','adjourn']),...fp},[W,EV],'('+qualifies+') && (args.operation == "petition" || reads.wm.convergence.petition)',[
 eff('world_matters','p7_petition',{},'args.operation == "petition"'),eff('evidence','p7_residual',{},'args.operation == "examine"','network'),eff('world_matters','p7_residual',{},'args.operation == "examine"'),eff('settlements','p7_compact',{...Object.fromEntries(Object.keys(dims).map(k=>[k,F('args.'+k)])),compensation_due:F('args.justice == "compensation"'),recognition_due:F('args.justice == "recognition_review"'),audit_due:F('args.accountability == "independent_audit"'),source_exposure:F('args.history == "attributed_public"')},'args.operation == "settle"'),eff('institutional_records','p7_compact',{...Object.fromEntries(Object.keys(dims).map(k=>[k,F('args.'+k)])),compensation_due:F('args.justice == "compensation"'),recognition_due:F('args.justice == "recognition_review"'),audit_due:F('args.accountability == "independent_audit"'),source_exposure:F('args.history == "attributed_public"')},'args.operation == "settle"'),eff('world_matters','p7_compact',{},'args.operation == "settle"')], 'Reopen only with cross-source predicates. Negotiate historical disclosure, current stability, justice, political authority, sacred recognition and accountability independently. Residual inquiry questions the model; it does not finalize the deep cause. Late compacts leave lock/exclusion events intact.',30);
 // Ten reviewed families, two additional independent reusable slots. No dynamic
 // authority target: both slot paths and every operation are explicitly bounded.
 const patIds=patterns.map(a=>a.id), patEffects=[];
 for(const s of ['p0','p1']){const b='convergence.'+s;cmd('world_matters','p7_pattern_'+s,{family:S(64,patIds),claimant:S(64),request:B,reply:B,fulfil:B,disposition:S(32,['none','qualified_remedy','refer_review','withdraw']),due:I(0,37)}, {[b+'.family']:F('args.family'),[b+'.claimant']:F('args.claimant'),[b+'.opened']:true,[b+'.request']:F('world.'+b+'.request || args.request'),[b+'.reply']:F('world.'+b+'.reply || args.reply'),[b+'.disposition']:F('args.disposition'),[b+'.due']:F('args.due'),[b+'.fulfilled']:F('world.'+b+'.fulfilled || args.fulfil')});for(const role of ['request','reply']){cmd('evidence','p7_'+s+'_'+role,{}, {['convergence.'+s+'_'+role]:role==='request'?'Consenting claimant signed the declared Pattern request. Original held by the verifier; the requested remedy is not a judgment.':'Independent authorized custodian verified the declared Pattern comparison and returned a qualified response. The original remains in separate custody; historical cause is not decided.'});patEffects.push(eff('evidence','p7_'+s+'_'+role,{},'args.slot == "'+s+'" && args.operation == "'+role+'"','network'));}patEffects.push(eff('world_matters','p7_pattern_'+s,{family:F('args.family'),claimant:F('args.claimant'),request:F('args.operation == "request"'),reply:F('args.operation == "reply"'),fulfil:F('args.operation == "fulfil"'),disposition:F('args.disposition'),due:F('args.due')},'args.slot == "'+s+'"'));}
 tx('practice',{slot:S(2,['p0','p1']),family:S(64,patIds),claimant:{...S(64),minLength:1},operation:S(16,['open','request','reply','settle','fulfil']),disposition:S(32,['none','qualified_remedy','refer_review','withdraw']),due:I(0,37)},[W,PR],'reads.pr.breached && ('+['p0','p1'].map(s=>{const r='reads.wm.convergence.'+s;return '(args.slot == "'+s+'" && ((args.operation == "open" && !'+r+'.opened && args.disposition == "none" && args.due == reads.wm.day + 7) || ('+r+'.opened && args.family == '+r+'.family && args.claimant == '+r+'.claimant && args.due == '+r+'.due && ((args.operation == "request" && args.disposition == '+r+'.disposition) || (args.operation == "reply" && '+r+'.request && args.disposition == '+r+'.disposition) || (args.operation == "settle" && (args.disposition == "withdraw" || ('+r+'.request && '+r+'.reply && (args.disposition != "qualified_remedy" || !reads.wm.convergence.locked || reads.wm.convergence.compact_filed)))) || (args.operation == "fulfil" && '+r+'.reply && '+r+'.disposition == "qualified_remedy" && args.disposition == '+r+'.disposition)))))';}).join(' || ')+')',patEffects,'Open and process a consenting ordinary professional Case in a free static slot. Request and independent reply are per-instance records; remedy creates a duty, fulfil records delivery of its bounded certificate/service, not invented payment or historical proof. Family and due date cannot be rewritten.',10);
 // All reviewed catalog entries use a bounded supervised carrier. Canonical
 // rule/condition arguments are validated against the selected definition; they
 // are not user-authored powers. This slot is additional to the retained P5 Claim.
 const Catalog=O({item:S(96),rule:S(256),condition:S(256),primitive:S(32),tradition:S(16),consulted:B,active:B,applied:B,price_due:B});
 add('claims','catalog',Catalog,{item:'',rule:'No additional Claim.',condition:'No inspected carrier.',primitive:'none',tradition:'none',consulted:false,active:false,applied:false,price_due:false});
 const catArgs={item:S(96,catalog.map(a=>a.id)),rule:S(256,[...new Set(catalog.map(a=>a.canon.coreRule))]),condition:S(256,[...new Set(catalog.map(a=>a.canon.condition??a.canon.conditionFamily))]),primitive:S(32,[...new Set(catalog.map(a=>a.canon.primitive))]),tradition:S(16,['civic','church']),operation:S(16,['consult','invest','invoke','maintain','release']),acceptPrice:B};
 const C=read('claim','claims',['active','catalog']);
 const available=a=>{const p=a.canon.primitive.split('.').at(-1);return {memory:'reads.pr.verified && reads.pr.preserved',name:'reads.pr.verified',boundary:'('+pair('property','reads.ev.network')+')',echo:'('+pair('railway','reads.ev.network')+')',bond:'('+pair('company')+')',witness:'('+pair('headline')+')',form:'(reads.wm.convergence.p0.reply && reads.wm.convergence.p0.family == "matter.pattern.document_conservation") || (reads.wm.convergence.p1.reply && reads.wm.convergence.p1.family == "matter.pattern.document_conservation")',possibility:'('+pair('accident')+')'}[p]+(a.kind==='claim_archetype'?' && reads.pr.invested':'');};
 cmd('claims','p7_consult',catArgs,{'catalog.item':F('args.item'),'catalog.rule':F('args.rule'),'catalog.condition':F('args.condition'),'catalog.primitive':F('args.primitive'),'catalog.tradition':F('args.tradition'),'catalog.consulted':true,'catalog.active':false,'catalog.applied':false,'catalog.price_due':false});
 cmd('claims','p7_activate',{apply:B}, {'catalog.active':true,'catalog.applied':F('world.catalog.applied || args.apply'),'catalog.price_due':true});
 cmd('progression','p7_invest',{}, {invested:true,postponed:false});cmd('conditions','p7_invest',{}, {strained:false,text:'Invested through a maintained supervised carrier; Price remains enforceable.'});cmd('claims','p7_maintain',{}, {'catalog.price_due':false});cmd('claims','p7_release',{}, {'catalog.active':false,'catalog.applied':false,'catalog.consulted':false});
 const flag={name:'designation_held',memory:'carrier_held',boundary:'boundary_held',bond:'bond_held',echo:'echo_examined',form:'form_held',possibility:'alternatives_held',witness:'attribution_held'};
 cmd('world_matters','p7_claim_effect',Object.fromEntries(Object.keys(flag).map(k=>[k,B])),Object.fromEntries(Object.entries(flag).map(([k,v])=>['convergence.'+v,F('world.convergence.'+v+' || args.'+k)])));
 add('institutional_records','catalog',O({item:S(96),tradition:S(16),active:B}),{item:'',tradition:'none',active:false});
 cmd('institutional_records','p7_claim_record',{item:catArgs.item,tradition:catArgs.tradition,active:B},{'catalog.item':F('args.item'),'catalog.tradition':F('args.tradition'),'catalog.active':F('args.active')});
 cmd('world_matters','p7_claim_price',{due:B,filed:B},{report_due:F('args.due'),report_filed:F('args.filed')});
 const ca=tx('claim',catArgs,[W,EV,PR,C],'reads.pr.breached && ((args.operation == "consult" && !reads.claim.catalog.active) || (args.item == reads.claim.catalog.item && args.tradition == reads.claim.catalog.tradition && ((args.operation == "invest" && reads.claim.catalog.consulted && !reads.claim.catalog.active && args.acceptPrice) || (args.operation == "invoke" && reads.claim.catalog.active && args.acceptPrice && !reads.claim.catalog.price_due) || (args.operation == "maintain" && reads.claim.catalog.active) || args.operation == "release")))',[
 eff('claims','p7_consult',Object.fromEntries(Object.keys(catArgs).map(k=>[k,F('args.'+k)])),'args.operation == "consult"'),eff('claims','p7_activate',{apply:F('args.operation == "invoke"')},'args.operation == "invest" || args.operation == "invoke"'),eff('progression','p7_invest',{},'args.operation == "invest"'),eff('conditions','p7_invest',{},'args.operation == "invest"'),eff('world_matters','p7_claim_effect',Object.fromEntries(Object.keys(flag).map(k=>[k,F('args.primitive == "primitive.'+k+'"')])),'args.operation == "invoke"'),eff('claims','p7_maintain',{},'args.operation == "maintain"'),eff('claims','p7_release',{},'args.operation == "release"'),eff('institutional_records','p7_claim_record',{item:F('args.item'),tradition:F('args.tradition'),active:F('args.operation == "invest"')},'args.operation == "invest" || args.operation == "release"'),eff('world_matters','p7_claim_price',{due:F('args.operation != "maintain"'),filed:F('args.operation == "maintain"')},'args.tradition == "civic" && (args.operation == "invest" || args.operation == "invoke" || args.operation == "maintain")')], 'Use an earned catalog rule on its supervised consenting carrier only. Consultation establishes the stated inspected substrate, never unseen history. Investiture requires the maintained carrier and accepted civic reporting or sacred-custody Price; maintenance is required before invocation. Effects preserve the specific support, never rewrite history or reveal a hidden cause.',20);
 for(const primitive of catArgs.primitive.enum){const entries=catalog.filter(a=>a.canon.primitive===primitive);ca.validators.push({id:primitive,error:'Catalog identity, rule, condition and acquired support must agree.',formula:'args.primitive != '+JSON.stringify(primitive)+' || ('+entries.map(a=>'(args.item == '+JSON.stringify(a.id)+' && args.rule == '+JSON.stringify(a.canon.coreRule)+' && args.condition == '+JSON.stringify(a.canon.condition??a.canon.conditionFamily)+(a.kind==='claim_archetype'?' && reads.pr.invested':'')+')').join(' || ')+') && ('+available(entries.find(a=>a.kind==='claim_seed')??entries[0])+')'});}
 // Exact disclosure-safe scalar reconstruction, using existing grants only.
 pub.reads.find(r=>r.id==='network_evidence').fields.push('convergence');pub.reads.find(r=>r.id==='world_matters_main').fields.push('convergence');pub.reads.find(r=>r.id==='settlements_main').fields.push('convergence');pub.reads.find(r=>r.id==='claims_main').fields.push('catalog');
 const pred=predicates('reads.network_evidence');
 const Summary=O({cases:WM,evidence:ES,settlements:D('settlements').recordSchema.properties.convergence,layers:O({administrative:B,contradiction:B,deliberate:B,deep_inquiry:B}),predicates:O(Object.fromEntries(Object.keys(pred).map(k=>[k,B]))),eligible:B,catalog:Catalog});
 const out=D('opening_summary_projection');add(out.id,'convergence',Summary,{cases:wm,evidence:D('evidence').initial.convergence,settlements:D('settlements').initial.convergence,layers:{administrative:false,contradiction:false,deliberate:false,deep_inquiry:false},predicates:{incomplete:false,deliberate:false,dependence:false,active:false},eligible:false,catalog:D('claims').initial.catalog});
 const c=out.commands.find(c=>c.id==='publish');c.argsSchema=out.recordSchema;c.assign.convergence=F('args.convergence');
 for(const e of pub.effects.filter(e=>e.domainId===out.id))e.args.convergence={cases:fields(WM,'reads.world_matters_main.convergence'),evidence:fields(ES,'reads.network_evidence.convergence'),settlements:fields(D('settlements').recordSchema.properties.convergence,'reads.settlements_main.convergence'),layers:{administrative:F('reads.progression_main.breached'),contradiction:F(pred.incomplete),deliberate:F(pred.deliberate),deep_inquiry:F('reads.world_matters_main.convergence.deep_inquiry')},predicates:Object.fromEntries(Object.entries(pred).map(([k,v])=>[k,F(v)])),eligible:F(Object.values(pred).join(' && ')),catalog:fields(Catalog,'reads.claims_main.catalog')};
 // The existing opening Graph root carries the bounded acquired P7 Evidence
 // bundle. No extra publication command, parallel index or arbitrary node target.
 const graph=D('investigation_nodes_projection'), graphShape=O({evidence:ES,predicates:O(Object.fromEntries(Object.keys(pred).map(k=>[k,B]))),eligible:B,hearing:Final});
 graph.recordSchema.properties.convergence={...graphShape,required:[]};graph.recordSchema.required.push('convergence');graph.initial.convergence={};graph.commands.find(c=>c.id==='bootstrap').assign.convergence={};
 const rootEffect=pub.effects.find(e=>e.domainId===graph.id&&e.recordId==='main');
 const rootArgs=Object.fromEntries(Object.entries(rootEffect.args).map(([k,v])=>[k,graph.recordSchema.properties[k]]));
 cmd(graph.id,'convergence_root',{...rootArgs,convergence:graphShape},{...Object.fromEntries(Object.keys(rootArgs).map(k=>[k,F('args.'+k)])),convergence:F('args.convergence')});
 rootEffect.commandId='convergence_root';rootEffect.args.convergence={evidence:fields(ES,'reads.network_evidence.convergence'),predicates:Object.fromEntries(Object.entries(pred).map(([k,v])=>[k,F(v)])),eligible:F(Object.values(pred).join(' && ')),hearing:fields(Final,'reads.settlements_main.convergence.hearing')};
 information.sources.find(s=>s.id==='investigation.nodes').fields.push(['convergence']);
 information.sources.push({id:'player.convergence.status',kind:'application',scopeId:'session',domainId:out.id,semantic:'truth',fields:['cases','settlements','predicates','eligible','layers','catalog'].map(k=>['convergence',k])},{id:'player.convergence.evidence',kind:'application',scopeId:'session',domainId:out.id,semantic:'truth',fields:[['convergence','evidence']]});
 // Intent receives compact Case records; detailed evidence remains in the
 // existing display/reflection Graphs. Do not pay for the same full records in
 // two observation Views, or let a new empty bundle evict old acquired Cases.
 const brief=information.sources.find(s=>s.id==='investigation.nodes');
 information.sources.push({...structuredClone(brief),id:'investigation.details'});
 brief.fields=[['text'],['subject'],['verified'],['detail','procedure'],['detail','settlement','disposition'],['detail','incomplete'],['detail','rights_depend'],['detail','active_contradiction'],['detail','organized_movement'],['convergence','eligible'],['convergence','predicates']];
 for(const g of information.graphs)g.nodeSource='investigation.details';
 for(const v of information.views){
  v.sources=information.sources.map(s=>s.id).filter(id=>id!=='player.convergence.evidence');
  if(v.id==='player.overview'||v.id==='claim.advisor.context')v.sources=v.sources.filter(id=>id!=='investigation.details');
  else v.sources=v.sources.filter(id=>id!=='investigation.nodes');
 }

 opening.bridge.bindings=logic.transactions.filter(t=>t.intent.expose).map(t=>({id:t.id.replaceAll('.','_'),kind:'action',target:{transactionId:t.id},inputSchema:t.inputSchema,outputSchema:{type:'object',properties:{},additionalProperties:false}}));
 opening.budget={publicationReads:pub.reads.length,publicationCommands:pub.effects.length,transactions:logic.transactions.length};
 if(logic.transactions.length>64||pub.reads.length>16)throw new Error('P7 declaration budget');
 return opening;
}
