import {mountNativeFrontend} from '/scripts/native/frontend/runtime.js';
import {frontendHttpTransport} from '/scripts/native/frontend/bridge.js';
import {createHeadlessConversation} from '/scripts/native/frontend/conversation.js';
const compiled=await (await fetch('/compiled')).json();
let draft='',snapshot={revision:{revisionId:(await (await fetch('/snapshot')).json()).revision}};
const current={active:true,get snapshot(){return snapshot;},generationProjection:{state:'idle',text:'',error:''}};
const conversation=createHeadlessConversation({runtime:current,composer:{getDraft:()=>draft,setDraft:t=>{draft=t;},appendDraft:t=>{draft+=t;},clearDraft:()=>{draft='';},focus:()=>{},submit:async({revision})=>{current.generationProjection.state='running';try{const r=await fetch('/composer-submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:draft,revision})});if(!r.ok)throw Error('Composer submission failed');draft='';}finally{current.generationProjection.state='idle';}}},stop:()=>{}});
const diagnosticView=document.createElement('pre');diagnosticView.id='p8-diagnostics';diagnosticView.style.cssText='position:fixed;bottom:0;right:0;background:white;color:maroon;z-index:9999;max-width:80vw';document.body.append(diagnosticView);
window.diagnostics=[];window.runtime=await mountNativeFrontend({entry:compiled.entry,mode:'full',onDiagnostic:d=>{window.diagnostics.push(d);diagnosticView.textContent=JSON.stringify(d);},bridgeTransport:frontendHttpTransport({sessionId:compiled.sessionId}),onBridgeRevision:revision=>{snapshot={revision:{revisionId:revision}};},onBridgeEpoch:async()=>{snapshot={revision:{revisionId:(await (await fetch('/snapshot')).json()).revision}};},hostServices:conversation,loadBytes:p=>Uint8Array.from(atob(compiled.files[p]),c=>c.charCodeAt(0)),surfaceHost:{mount(){const container=document.createElement('div');container.style.height='100%';document.getElementById('surface').append(container);return {container,unmount:()=>container.remove()};}}});
