// Build-time declaration compiler. No Package-side runtime or authority evaluator.
// Runtime effects are exclusively declarative Core transactions and Lifecycle commands.
export function compileOpening({manifest, contract, backgrounds, seeds, caseAsset}) {
 const F = formula => ({formula});
 const S = (maxLength=256, values) => ({type:'string',maxLength:values?Math.max(maxLength,...values.map(v=>v.length)):maxLength,...(values?{enum:values}:{})});
 const I = (minimum=0,maximum=30) => ({type:'integer',minimum,maximum});
 const B = {type:'boolean'};
 const O = properties => ({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
 const empty=O({}); const domains=[]; const automations=[];
 const domain=(id,scopeId,properties,initial,records=['main'])=>{
  const d={id,scopeId,schemaVersion:1,recordSchema:O(properties),initial,commands:[],retention:{maxItems:64,maxLogicalBytes:65536,keepPinned:true,keepReferenced:true}};
  domains.push(d); command(id,'bootstrap',{},initial);
  for(const recordId of records)automations.push({id:id+'.'+recordId+'.bootstrap',scopeId,trigger:{kind:'experience.ready'},action:{kind:'app.command',domainId:id,commandId:'bootstrap',recordId,args:{}},maxCatchUp:1});
  return d;
 };
 const command=(id,cid,args,assign)=>{domains.find(d=>d.id===id).commands.push({id:cid,argsSchema:O(args),event:id+'.'+cid,assign});};
 const patch=(id,cid,values)=>{const d=domains.find(d=>d.id===id);const props=Object.fromEntries(Object.keys(values).map(k=>[k,d.recordSchema.properties[k]]));command(id,cid,props,Object.fromEntries(Object.keys(values).map(k=>[k,F('args.'+k)])));return values;};
 const effect=(id,cid,args={},recordId='main',when)=>({kind:'app.command',domainId:id,commandId:cid,recordId,args,...(when?{when}:{})});
 const read=(id,domainId,fields,recordId='main')=>({id,domainId,recordId,fields});
 const life=domain('player_life','session',{step:I(0,6),name:S(64),pronouns:S(64),age:I(18,100),appearance:S(),origin:S(96),prior:S(96),faith:S(96),anchor_name:S(64),relationship:S(32),place:S(96),reason:S(),familiarity:S(),introduction:S(96),faith_practice:S(),origin_familiarity:S(),licensed:B},{step:0,name:'',pronouns:'',age:18,appearance:'',origin:'',prior:'',faith:'',anchor_name:'',relationship:'',place:'',reason:'',familiarity:'',introduction:'',faith_practice:'',origin_familiarity:'',licensed:false});
 domain('entities','world',{name:S(64),alive:B,role:S(96),location:S(96),history:S()},{name:'',alive:true,role:'Ordinary citizen',location:'Civil Verifier practice',history:''},['anchor']);
 domain('relations','world',{text:S(),kind:S(32),maintained:B},{text:'No personal relation created yet.',kind:'uncreated',maintained:false});
 domain('progression','session',{current_source:S(32),old_source:S(32),verified:B,preserved:B,family:B,breached:B,postponed:B,seed:S(96),taught:B,invested:B},{current_source:'',old_source:'',verified:false,preserved:false,family:false,breached:false,postponed:false,seed:'',taught:false,invested:false});
 domain('evidence','world',{text:S(),subject:S(64),provenance:S(96),custody:S(96),known:B,verified:B},{text:'Not acquired',subject:'',provenance:'',custody:'',known:false,verified:false},['mortuary','insurance','register','police']);
 domain('beliefs','world',{text:S(),kind:S(32),status:S(32),channel:S(32),actor:S(64),testimony:S(),testimony_status:S(32),testimony_channel:S(32)},{testimony_status:'suspected',testimony_channel:'told_by',testimony:'No family testimony recorded.',actor:manifest.actors[0].actorId,text:'No testimony or theory recorded.',kind:'hypothesis',status:'suspected',channel:'inference'},['main']);
 domain('player_matters','session',{text:S(),status:S(32),case_state:S(32)},{text:'Complete your ordinary identity, origin, prior life, faith, living Anchor and reason to practice.',status:'open',case_state:'creation'},['main','lead']);
 domain('world_matters','world',{day:I(),next_tick:I(0,50000),rent:I(0,3000),anchor_missed:B,anchor_kept:B,report_due:B,report_filed:B},{day:0,next_tick:1440,rent:0,anchor_missed:false,anchor_kept:false,report_due:false,report_filed:false});
 domain('settlements','world',{disposition:S(32),assertion:S(),accepted_by:S(96),changed:S(),unresolved:S(),benefit:S(),cost:S()},{disposition:'none',assertion:'No disposition submitted.',accepted_by:'none',changed:'none',unresolved:'Identity conflict remains.',benefit:'none',cost:'none'});
 domain('institutional_records','world',{reported:B,review:B,protected:B,referred:B,claim_record:B},{reported:false,review:false,protected:false,referred:false,claim_record:false},[]);
 domain('claims','world',{seed:S(96),rule:S(),jurisdiction:S(96),anchor:S(128),price:S(128),tradition:S(32),active:B},{seed:'',rule:'No formal Claim.',jurisdiction:'none',anchor:'none',price:'none',tradition:'none',active:false});
 domain('conditions','world',{text:S(),strained:B},{text:'Ordinary, unbreached.',strained:false});
 // Rebuildable public projections: no raw Canon, institutional motive or unacquired record is read.
 const pubReads=[],pubEffects=[],sources=[];
 function projection(sourceId,authorityId,record,fields,semantic='truth',guard) {
  const a=domains.find(d=>d.id===authorityId),pid=sourceId.replaceAll('.','_')+'_projection';
  let p=domains.find(d=>d.id===pid);
  const properties=Object.fromEntries(fields.map(k=>[k,a.recordSchema.properties[k]]));
  if(!p){p=domain(pid,'session',properties,Object.fromEntries(fields.map(k=>[k,a.initial[k]])),[]);patch(pid,'publish',Object.fromEntries(fields.map(k=>[k,null])));sources.push({id:sourceId,kind:'application',scopeId:'session',domainId:pid,semantic,fields:fields.map(k=>[k]),...(semantic==='belief'?{actorField:'actor',statusField:'status',channelField:'channel'}:{})});}
  const rid=authorityId+'_'+record;
  pubReads.push(read(rid,authorityId,[...new Set([...fields,...(guard?['known']:[])])],record));
  pubEffects.push(effect(pid,'publish',Object.fromEntries(fields.map(k=>[k,F('reads.'+rid+'.'+k)])),record,guard?'reads.'+rid+'.known':undefined));
 }
 projection('player.status','player_life','main',['step','name','pronouns','age','appearance','origin','prior','faith','anchor_name','relationship','place','reason','familiarity','introduction','faith_practice','origin_familiarity']);
 projection('player.progression','progression','main',['current_source','old_source','verified','preserved','family','breached','postponed','seed','taught','invested']);
 for(const r of ['mortuary','insurance','register','police'])projection('investigation.nodes','evidence',r,['text','subject','provenance','custody','verified'],'truth',true);
 projection('player.epistemic','beliefs','main',['text','kind','status','channel','actor','testimony','testimony_status','testimony_channel'],'belief');

 const epistemic=sources.find(s=>s.id==='player.epistemic');epistemic.fields=epistemic.fields.filter(f=>!f[0].startsWith('testimony'));sources.push({...epistemic,id:'player.testimony',fields:[['testimony']],statusField:'testimony_status',channelField:'testimony_channel'});
 projection('player.claim','claims','main',['seed','rule','jurisdiction','anchor','price','tradition','active']);
 projection('player.settlement','settlements','main',['disposition','assertion','accepted_by','changed','unresolved','benefit','cost']);
 projection('player.obligations','world_matters','main',['day','rent','anchor_missed','report_due','report_filed']);
 sources.push({id:'player.matters',kind:'application',scopeId:'session',domainId:'player_matters',semantic:'open_loop',fields:[['text']],statusField:'status'});
 domain('investigation_edges','session',{from:S(64),to:S(64),text:S()},{from:'main',to:'main',text:''},[]);
 patch('investigation_edges','publish',{from:null,to:null,text:null});
 sources.push({id:'investigation.edges',kind:'application',scopeId:'session',domainId:'investigation_edges',semantic:'truth',fields:[['from'],['to'],['text']]});
 pubEffects.push(effect('investigation_nodes_projection','publish',{subject:'elias_rook',text:'Second Death: acquired sources concern incompatible identity records; no hidden clue total.',provenance:'Civil verification mandate',custody:'Player case reference',verified:false},'main'));
 for(const r of ['mortuary','insurance','register','police'])pubEffects.push(effect('investigation_edges','publish',{from:'main',to:r,text:'Acquired source relevant to identity conflict; not a causal conclusion.'},r,'reads.evidence_'+r+'.known'));
 const pp=domains.find(d=>d.id==='player_progression_projection');
 for(const key of ['candidate_one','candidate_two']){pp.recordSchema.properties[key]=S();pp.recordSchema.required.push(key);pp.initial[key]='';}
 const pc=pp.commands.find(c=>c.id==='publish');for(const key of ['candidate_one','candidate_two']){pc.argsSchema.properties[key]=S();pc.argsSchema.required.push(key);pc.assign[key]=F('args.'+key);}
 sources.find(s=>s.id==='player.progression').fields.push(['candidate_one'],['candidate_two']);
 const pe=pubEffects.find(e=>e.domainId===pp.id),condition='reads.progression_main.breached && reads.progression_main.verified && reads.progression_main.preserved && !reads.progression_main.invested';
 pe.args.candidate_one='';pe.args.candidate_two='';pe.when='!('+condition+')';
 pubEffects.push({...structuredClone(pe),when:condition,args:{...pe.args,candidate_one:'Unlost Evidence: retain one personally verified contradictory fact. No protection of other minds or reconstruction of destroyed records.',candidate_two:'A Name Does Not Fit: notice mismatch in one present examined identity support. No true-name revelation or universal forgery detection.'}});
 const logic={schemaVersion:3,commands:[],reducers:[{type:'OpeningAction',payloadSchema:O({verb:S(64),outcome:S(32)}),assign:{interactionCount:F('world.interactionCount + 1')}}],rules:[],interpretations:[],derivedPublications:[{id:'opening.publish',reads:pubReads,effects:pubEffects}],transactions:[]};
 const LR=read('life','player_life',['step','prior','origin','faith','licensed']);
 const PR=read('progress','progression',['current_source','old_source','verified','preserved','family','breached','postponed','seed','taught','invested']);
 function tx(id,verb,props,reads,allowed,effects,notice,minutes=0) {
  const t={id:'opening.'+id,verb:id,inputSchema:O(props),intent:{expose:true,description:notice},reads,validators:[],resolution:{kind:'deterministic',cases:allowed?[{id:'impossible',when:'!('+allowed+')',outcome:'impossible'}]:[],fallback:'automatic'},effects:[{kind:'world.event',type:'OpeningAction',payload:{verb:id,outcome:F('resolution.outcome')}},...effects.map(e=>({...e,when:e.when?'('+e.when+') && resolution.outcome != "impossible"':'resolution.outcome != "impossible"'})),...(minutes?[{kind:'clock.advance',commandId:'advance',ticks:typeof minutes==='number'?minutes:F(minutes),when:'resolution.outcome != "impossible"'}]:[])],derivedPublications:['opening.publish'],receipt:{schema:O({verb:S(64),outcome:S(32),notice:S(1024)}),projection:{verb,outcome:F('resolution.outcome'),notice},maxBytes:2048}};

  logic.transactions.push(t);return t;
 }
 const set=(d,cid,values,record='main',when)=>{patch(d,cid,values);return effect(d,cid,values,record,when);};
 const advanceStep=(step,props,values)=>set('player_life','step_'+step,{step,...values});
 tx('identity','create_identity',{name:{...S(64),minLength:1},pronouns:S(64),age:I(18,100),appearance:S()},[LR],'reads.life.step == 0',[advanceStep(1,{}, {name:F('args.name'),pronouns:F('args.pronouns'),age:F('args.age'),appearance:F('args.appearance')})],'Step 1: ordinary adult identity only. Descriptions grant no external facts, offices, ancestry or powers.');
 for(const [kind,step,key] of [['origin',2,'origin'],['prior_life',3,'prior'],['faith',4,'faith']]) {
  const choices=backgrounds.filter(a=>a.kind===kind);
  const effects=[];
  for(const a of choices){const vals={step,[key]:a.id,...(kind==='origin'?{origin_familiarity:a.canon.knowledgeAccess[0]}:{}),...(kind==='faith'?{faith_practice:a.canon.knowledgeAccess[0]}:{familiarity:a.canon.knowledgeAccess[0],introduction:a.canon.institution})};effects.push(set('player_life','choose_'+a.id.replaceAll('.','_'),vals,'main','args.choice == '+JSON.stringify(a.id)));}
  tx(kind,'choose_'+kind,{choice:S(96,choices.map(a=>a.id))},[LR],'reads.life.step == '+(step-1),effects,'Choose one curated '+kind+'. Familiarity and ordinary introductions grant interpretation, not general restricted access.');
 }
 tx('anchor','create_anchor',{name:{...S(64),minLength:1},relationship:S(32,['parent','sibling','spouse','lover','friend','mentor','colleague','partner']),place:S(96,['none','home','office','parish','community'])},[LR],'reads.life.step == 4',[
 advanceStep(5,{}, {anchor_name:F('args.name'),relationship:F('args.relationship'),place:F('args.place')}),set('entities','create_anchor',{name:F('args.name'),alive:true,role:'Ordinary citizen',location:'Civil Verifier practice',history:'A living important person with an established ordinary relationship.'},'anchor'),set('relations','create',{text:'Living Personal Anchor; next promised visit by the second day.',kind:F('args.relationship'),maintained:true})],'Step 5: instantiate one living ordinary Personal Anchor; no hidden supernatural biography.');
 tx('reason','begin_practice',{reason:{...S(),minLength:1}},[LR],'reads.life.step == 5',[advanceStep(6,{}, {reason:F('args.reason'),licensed:true}),set('entities','client',{name:'Elias Rook',alive:false,role:'Deceased verification client',location:'Medical examiner custody',history:'Current identity supported by the family mandate.'},'elias_rook'),set('player_matters','begin',{text:caseAsset.perspective.publicDescription,status:'open',case_state:'active'})],'Step 6: independent licensed Civil Verifier with a family mandate, ordinary records access, a small practice and daily rent. No faction membership or formal Claim.');
 const ready='reads.life.step == 6';
 const records=[
 ['mortuary','observe','inspect_death','Recent examination records Elias Rook deceased; current identity documents match the body.','Medical examiner: authorized family copy','prior_life.medical'],
 ['insurance','access','request_continuity','Insurance entries record decades of continuous payments and household identity for Elias Rook.','Insurer: family mandate extract','prior_life.insurance'],
 ['register','verify','request_old_register','Certified civil register records Elias Rook dead at Eastbank approximately forty years ago.','Civil registry: certified entry','prior_life.legal'],
 ['police','access','request_certified_copy','Police custody copy independently preserves the old Eastbank death registration for Elias Rook.','Police: certified custody extract','prior_life.military']];
 for(const [record,verb,method,text,provenance,prior] of records){
  const support=set('progression','support_'+record,{[record==='mortuary'||record==='insurance'?'current_source':'old_source']:record});
  const e=set('evidence','acquire_'+record,{text,subject:'elias_rook',provenance,custody:'Player authorized copy',known:true,verified:true},record);
  tx('acquire_'+record,verb,{method:S(32,[method])},[LR],ready,[e,support],'Authorized '+method+'. Core information is Automatic; this certifies source provenance, not which incompatible death is Truth.',10);
  tx('familiar_'+record,verb,{method:S(32,['professional_introduction'])},[LR],ready+' && ('+({mortuary:['prior_life.medical'],insurance:['prior_life.insurance'],register:['prior_life.legal','prior_life.church_school','prior_life.administration'],police:['prior_life.military','prior_life.journalism','prior_life.rail_work']}[record]).map(id=>'reads.life.prior == '+JSON.stringify(id)).join(' || ')+')',[effect('evidence','acquire_'+record,e.args,record),support],'Background-specific professional introduction obtains the same source without the ten-minute clerical delay. Alternative public route remains available.');
 }
 tx('family','interview',{method:S(32,['ask_with_consent'])},[LR],ready,[set('entities','family',{name:'Ada Rook',alive:true,role:'Surviving adult sister',location:'Rook household',history:'Known living household relationship with Elias.'},'ada_rook'),set('relations','family',{text:'Ada is Elias Rook’s surviving sister.',kind:'sibling',maintained:true},'family'),set('beliefs','testimony',{testimony:'Ada Rook reports decades of household continuity. Attributed, unverified testimony; not complete historical Truth.'}),set('progression','family',{family:true})],'Family testimony is a report. Respecting her consent preserves relationship continuity.',10);
 const er=['mortuary','insurance','register','police'].map(r=>read(r,'evidence',['known','verified'],r));
 const pair='reads.progress.current_source != "" && reads.progress.old_source != ""';
 tx('compare','verify',{method:S(32,['compare_independent_sources'])},[PR],pair,[set('progression','verified',{verified:true}),set('player_matters','finding',{text:'Finding: independent authentic chains support incompatible deaths. Cause remains unknown; preserve both, investigate another source, or commit a qualified disposition.',status:'open',case_state:'active'})],'Verify independent record chains. Finding: authentic records conflict; neither identifies the deep cause.',10);
 tx('preserve','intervene',{method:S(32,['separate_and_witness'])},[LR,PR],ready+' && reads.progress.verified && !reads.progress.breached',[set('progression','breach',{preserved:true,breached:true}),set('conditions','breach',{text:'Breached and unsettled: intermittent contradiction sensitivity, not a formal power.',strained:true})],'Keep the independently verified incompatible facts separated and personally witnessed. First Breach creates discrete verified/preserved Imprints, never a class or automatic Claim. Two narrow supported Seeds are Unlost Evidence and A Name Does Not Fit.');
 for(const id of ['hypothesis','lead'])tx(id,'create_'+id,{text:{...S(),minLength:1}},[LR],ready,[id==='hypothesis'?set('beliefs','theory',{text:F('args.text'),kind:'hypothesis',status:'suspected',channel:'inference'}):set('player_matters','lead',{text:F('args.text'),status:'open'},'lead')],'Player proposal only. It cannot generate evidence or change Truth.');
 tx('private_access','access',{method:S(32,['demand_secret_archive'])},[LR],ready,[set('player_matters','denial',{text:'Restricted archive request denied: the civil license is not a warrant. Seek an authorized civil or police extract; investigation continues.',status:'open',case_state:'active'})],'Denied private access creates a recorded alternative route, never hidden institutional knowledge.',10).resolution.fallback='denied';
 const eligible=ready+' && reads.progress.breached && reads.progress.verified && reads.progress.preserved && !reads.progress.invested';
 for(const seed of seeds.filter(s=>s.canon.runtimeEligibility.length>0))tx('seed_'+seed.id.split('.').at(-1),'choose_seed',{seed:S(96,[seed.id])},[LR,PR],eligible,[set('progression','seed_'+seed.id.split('.').at(-1),{seed:seed.id,postponed:false})],seed.perspective.playerDescription+'. Candidate only. '+seed.canon.forbiddenExtensions.join('; '));
 tx('postpone','postpone_investiture',{},[LR,PR],eligible,[set('progression','postpone',{postponed:true,seed:''})],'Remain breached but uninvested. No formal Price yet; sensitivity is unreliable and unresolved strain persists.');
 tx('consult','consult_stabilization',{method:S(32,['qualified_civic_or_church_consultation'])},[LR,PR],eligible,[set('progression','taught',{taught:true})],'Qualified consultation explains a narrow Seed, institutional Anchor and reporting or witnessed-record maintenance Price. It does not grant self-Investiture or secret cosmology.',30);
 for(const seed of seeds.filter(s=>s.canon.runtimeEligibility.length>0))for(const tradition of ['civic','church'])tx('stabilize_'+seed.id.split('.').at(-1)+'_'+tradition,'stabilize',{tradition:S(32,[tradition]),seed:S(96,[seed.id]),acceptPrice:{type:'boolean',enum:[true]}},[LR,PR],eligible+' && reads.progress.taught && reads.progress.seed == '+JSON.stringify(seed.id),[
 set('conditions','stabilized_'+seed.id.split('.').at(-1)+'_'+tradition,{text:'Breach stabilized under its recorded Anchor and Price.',strained:false}),set('claims','grant_'+seed.id.split('.').at(-1)+'_'+tradition,{seed:seed.id,rule:seed.canon.coreRule,jurisdiction:seed.canon.starterJurisdiction,anchor:tradition==='civic'?'Licensed personally signed contradiction record':'Personally witnessed record under a communal oath',price:tradition==='civic'?'Report dangerous contradictions; institutional exposure':'Maintain the witnessed carrier and do not knowingly deny its recorded fact',tradition,active:true}),set('institutional_records','record_claim_'+seed.id.split('.').at(-1)+'_'+tradition,{claim_record:true}),set('progression','invested_'+seed.id.split('.').at(-1)+'_'+tradition,{invested:true,postponed:false}),set('world_matters','price_'+seed.id.split('.').at(-1)+'_'+tradition,{report_due:tradition==='civic',report_filed:false})],'Earned formal Claim only after independent actions, Breach, chosen Seed, consultation, accepted Anchor and Price. '+seed.canon.forbiddenExtensions[0],30);
 tx('invoke','invoke_claim',{target:S(32,['examined_identity'])},[LR,read('claim','claims',['active','seed'])],ready+' && reads.claim.active',[set('player_matters','claim_notice',{text:'The narrow Claim preserves recognition or detects mismatch in this personally examined identity support. It proves neither hidden Name nor cause and does not compel recognition.',status:'open',case_state:'active'})],'Apply only the granted investigative rule to already examined identity support. No new historical evidence or universal detection.',5);
 tx('test_copy','test',{method:S(32,['examine_authorized_copy'])},[read('copy','evidence',['known'],'mortuary')],'reads.copy.known',[set('player_matters','test_copy',{text:'The examined copy has consistent certification; provenance is not proof of the underlying historical explanation.',status:'open',case_state:'active'})],'Examine an acquired copy without manufacturing new historical evidence.',5);
 const dispositions={report_new:['The recent death is reported; old entry retained as disputed.','Civil registry','New death notice accepted, no historical erasure.','Family may proceed with qualified paperwork.','Professional accountability remains.'],challenge_old:['The old death registration is formally challenged, not deleted.','Civil registry','Review docket opened; current identity protected pending review.','Family obtains a review route.','Further certified evidence required.'],protect_family:['Protect present family continuity without adjudicating old history.','Ada Rook','Private arrangement preserves current household recognition.','Surviving family protected.','No binding public ruling; insurer may dispute.'],notify_authority:['Report a persistent identity contradiction, not a proven cosmological cause.','Abnormal authority intake','Referral accepted; no abnormal office conferred.','Specialist review requested.','Reporting obligation and exposure.'],abandon:['Withdraw without a conclusion; facts remain unresolved.','Civil practice','Case dormant; no false Truth is installed.','No compelled Investiture.','Family must seek another verifier.']};
 for(const [id,[assertion,accepted_by,changed,benefit,cost]]of Object.entries(dispositions))tx('settle_'+id,'settle_matter',{disposition:S(32,[id])},[LR],ready,[set('institutional_records','record_'+id,{reported:id==='report_new',review:id==='challenge_old',protected:id==='protect_family',referred:id==='notify_authority'}),set('settlements','settle_'+id,{disposition:id,assertion,accepted_by,changed,unresolved:'The cause of incompatible identity chains remains unknown.',benefit,cost}),set('player_matters','close_'+id,{text:assertion,status:'closed',case_state:id==='abandon'?'dormant':'settled'}),...(id==='notify_authority'?[set('world_matters','report',{report_filed:true,report_due:false})]:[])],'Commit a qualified disposition under incomplete knowledge. Wrong theories do not rewrite Evidence or Truth; consequences remain and the campaign continues.',10);
 tx('reopen','reopen_matter',{},[LR],ready,[set('player_matters','reopen',{text:'Reopened identity inquiry; previous disposition remains in committed history.',status:'open',case_state:'reopened'})],'Reopen inquiry without erasing the previous Settlement.');
 tx('visit','downtime',{method:S(32,['keep_anchor_appointment'])},[LR],ready,[set('relations','visit',{maintained:true,text:'A real visit maintained the ordinary Personal Anchor relationship.'}),set('world_matters','visit',{anchor_missed:false,anchor_kept:true})],'Spend time with the living Anchor; concrete continuity, not Humanity points.',30);
 tx('wait','advance_time',{minutes:I(1,2880)},[LR],ready,[],'Advance the canonical clock; bounded daily rent and the family appointment proceed. Day 31 rejects atomically.','args.minutes');
 command('world_matters','day',{}, {day:F('world.day + 1'),next_tick:F('world.next_tick + 1440'),rent:F('world.rent + 10')});
 command('world_matters','missed',{}, {anchor_missed:F('!world.anchor_kept')});
 const day=tx('day','simulation_day',{day:I(0,29)},[],null,[effect('world_matters','day'),effect('world_matters','missed',{},'main','args.day == 1')],'Daily obligation accounting.');day.origin='simulation';day.intent.expose=false;
 domains.push(structuredClone(contract.lifecycleRuntime.domains.find(d=>d.id==='agendas')));
 const lifecycle={...contract.lifecycleRuntime,domains,automations,workflows:[],interactions:[]};
 const simulation={schemaVersion:1,clockId:'world',policy:{maxSteps:3,maxDeliberations:1,maxAdvanceTicks:2880},jobs:[{id:'opening.calendar',scopeId:'world',reads:[read('calendar','world_matters',['day','next_tick'])],enabled:'true',due:F('reads.calendar.next_tick'),priority:1,relevance:'cold',action:{kind:'transaction',transactionId:'opening.day',input:{day:F('reads.calendar.day')}}}]};
 const views=contract.informationRuntime.views.map(v=>({...v,sources:sources.map(s=>s.id),knowledge:false,memory:false}));
 const information={schemaVersion:1,sources,views,actors:[],graphs:structuredClone(contract.informationRuntime.graphs)};
 // Native typed bindings and free-text resolve to exactly these same transaction declarations.
 const bridge={version:1,bindings:logic.transactions.filter(t=>t.intent.expose).map(t=>({id:t.id.replaceAll('.','_'),kind:'action',target:{transactionId:t.id},inputSchema:t.inputSchema,outputSchema:{type:"object",properties:{},additionalProperties:false}}))};
 return {logic,lifecycle,simulation,information,bridge,budget:{publicationReads:pubReads.length,publicationCommands:pubEffects.length}};
}
