// Authored structural grammars. Core owns selection, eligibility and canonization.
export const renewalPolicy = {
    schemaVersion: 1, maxActive: 1, maxRecent: 64, cooldownTicks: 90 * 1440, minimumDistance: 3, maxEntities: 96,
    places: [
        { id: 'eastbank', name: 'Eastbank', kind: 'district', districtId: '', function: 'mixed riverside quarter' },
        { id: 'record_hall', name: 'Civil Record Hall', kind: 'location', districtId: 'eastbank', function: 'public archive' },
        { id: 'river_foundry', name: 'River Foundry', kind: 'business', districtId: 'eastbank', function: 'metalworking' },
        { id: 'old_quay', name: 'Old Quay', kind: 'location', districtId: 'eastbank', function: 'river landing' },
    ],
    grammars: [
        { id: 'document_fraud', responseTicks: 30 * 1440, trigger: 'A current record conflicts with a claimant’s document.', subject: ['office applicant', 'licensed witness', 'displaced worker'], roles: ['claimant versus registrar', 'witness versus employer', 'heir versus custodian'], truth: ['substituted signature', 'lawful name changed', 'coerced declaration'], anomaly: ['none', 'ink retains an erased name', 'seal echoes a former owner'], path: ['compare public register', 'trace attesting witnesses', 'inspect original seal'], stakes: ['professional eligibility', 'family standing', 'access to premises'], resolution: ['correct record', 'restitution to claimant', 'preserve disputed evidence'], actions: ['inspect', 'compare', 'confront'], historyRequired: false },
        { id: 'industrial_harm', responseTicks: 30 * 1440, trigger: 'A workplace complaint exposes a conflict over safety and livelihood.', subject: ['apprentice', 'shift witness', 'maintenance contractor'], roles: ['worker versus manager', 'neighbors versus operator', 'inspector versus sponsor'], truth: ['inspection suppressed', 'repair diverted', 'hazard misidentified'], anomaly: ['none', 'resonant machinery', 'contaminated residue'], path: ['reconstruct shift', 'test residue', 'follow repair records'], stakes: ['safe access', 'public trust', 'continued livelihood'], resolution: ['repair hazard', 'restitution to workers', 'record unresolved liability'], actions: ['survey', 'test', 'hear'], historyRequired: false },
        { id: 'family_obligation', responseTicks: 30 * 1440, trigger: 'A living family member contests an obligation attached to a household.', subject: ['adult child', 'household witness', 'family creditor'], roles: ['heir versus creditor', 'siblings versus custodian', 'household versus office'], truth: ['promise misremembered', 'debt already discharged', 'beneficiary concealed'], anomaly: ['none', 'inherited echo', 'oath residue'], path: ['compare testimony', 'trace custody', 'reconstruct promise'], stakes: ['household reputation', 'custody of evidence', 'family obligation'], resolution: ['reconcile testimony', 'restitution to household', 'retain disputed obligation'], actions: ['listen', 'trace', 'mediate'], historyRequired: false },
        { id: 'institutional_conflict', responseTicks: 30 * 1440, trigger: 'A current institution’s stated procedure conflicts with local needs.', subject: ['petitioner', 'junior member', 'neighborhood delegate'], roles: ['member versus leadership', 'public versus office', 'custodian versus inspector'], truth: ['obsolete rule', 'concealed conflict of interest', 'jurisdiction misunderstood'], anomaly: ['none', 'binding charter echo', 'ritual boundary'], path: ['read charter', 'compare practice', 'hear affected parties'], stakes: ['access to service', 'institution legitimacy', 'local safety'], resolution: ['clarify procedure', 'restitution to petitioners', 'preserve dissent'], actions: ['review', 'interview', 'adjudicate'], historyRequired: false },
        { id: 'cold_case', responseTicks: 30 * 1440, trigger: 'Surviving evidence makes a dormant historical question actionable again.', subject: ['custodian of old evidence', 'descendant', 'later office holder'], roles: ['descendant versus institution', 'custodian versus claimant', 'current witness versus old record'], truth: ['missing corroboration found', 'earlier assumption disproven', 'concealed connection exposed'], anomaly: ['none', 'artifact memory', 'dormant residue'], path: ['verify provenance', 'compare historical testimony', 'inspect changed site'], stakes: ['historical reputation', 'inherited obligation', 'institutional accountability'], resolution: ['correct historical attribution', 'restitution to successor', 'retain qualified uncertainty'], actions: ['authenticate', 'reconstruct', 'reopen'], historyRequired: true },
    ],
};
export function compileRenewal(opening) {
    opening.lifecycle.lifetimes.renewal = structuredClone(renewalPolicy);
    return opening;
}
